#stack_prefix: default

network:
  stack_name: aem-network-stack

  internet_gateway:
    tag_name: AEM VPC Internet Gateway

  publish_dispatcher_elb:
    subnet_a:
      cidr_block: 10.0.10.0/25
      tag_name: AEM Publish Dispatcher ELB Subnet A
    subnet_b:
      cidr_block: 10.0.10.128/25
      tag_name: AEM Publish Dispatcher ELB Subnet B

  publish_dispatcher:
    subnet_a:
      cidr_block: 10.0.11.0/25
      tag_name: AEM Publish Dispatcher Subnet A
    subnet_b:
      cidr_block: 10.0.11.128/25
      tag_name: AEM Publish Dispatcher Subnet B

  publish:
    subnet_a:
      cidr_block: 10.0.12.0/25
      tag_name: AEM Publish Subnet A
    subnet_b:
      cidr_block: 10.0.12.128/25
      tag_name: AEM Publish Subnet B

  author:
    subnet_a:
      cidr_block: 10.0.13.0/25
      tag_name: AEM Author Subnet A
    subnet_b:
      cidr_block: 10.0.13.128/25
      tag_name: AEM Auhtor Subnet B

  author_dispatcher:
    subnet_a:
      cidr_block: 10.0.14.0/25
      tag_name: AEM Author Dispatcher Subnet A
    subnet_b:
      cidr_block: 10.0.14.128/25
      tag_name: AEM Author Dispatcher Subnet B

  tool:
    subnet_a:
      cidr_block: 10.0.15.0/25
      tag_name: AEM Tool Subnet A
    subnet_b:
      cidr_block: 10.0.15.128/25
      tag_name: AEM Tool Subnet B

  public_route_table:
    tag_name: AEM VPC Public Route Table

  private_route_table:
    tag_name: AEM VPC Private Route Table

  hosted_zone: aem.

bastion:
  stack_name: aem-bastion-stack
  key_pair_name: overwrite-me
  ami_id: ami-ccecf5af
  subnet_id: overwrite-me
  security_groups: overwrite-me

#TODO: create a new elastic ip option?
nat_gateway:
  stack_name: aem-nat-gateway-stack
  elastic_ip_allocation_id: eipalloc-32711957

endpoints:
  s3: aem-stack-builder

network_exports:
  stack_name: aem-network-exports-stack
  VPCId: vpc-12345678
  AuthorPublishDispatcherSubnet: subnet-12345678
  PublishDispatcherELBSubnetList: subnet-12345678,subnet-87654321
  PublishDispatcherSubnetList: subnet-12345678,subnet-87654321
  PublishSubnetList: subnet-12345678,subnet-87654321
  AuthorPrimarySubnet: subnet-12345678
  AuthorStandbySubnet: subnet-87654321
  AuthorELBSubnetList: subnet-12345678,subnet-87654321
  AuthorDispatcherELBSubnetList: subnet-12345678,subnet-87654321
  AuthorDispatcherSubnetList: subnet-12345678,subnet-87654321
  ToolSubnetList: subnet-12345678,subnet-87654321
  PublicRouteTable: rtb-77cd4413
  PrivateRouteTable: rtb-75cd4411
