---
AWSTemplateFormatVersion: '2010-09-09'

Description: >-
  Create the SSM Documents needed to orchestrate AEM in an AWS environment.

Parameters:

  DeployArtifactIncludeFileParameter:
    Type: String
    Default: AEM-DeployArtifact.yaml
    Description: >-
      The name of the file containing the DeployArtifact SSM command.

  DeployArtifactsIncludeFileParameter:
    Type: String
    Default: AEM-DeployArtifacts.yaml
    Description: >-
      The name of the file containing the DeployArtifacts SSM command.

  ExportPackageIncludeFileParameter:
    Type: String
    Default: AEM-ExportPackage.yaml
    Description: >-
      The name of the file containing the ExportPackage SSM command.

  ExportPackagesIncludeFileParameter:
    Type: String
    Default: AEM-ExportPackages.yaml
    Description: >-
      The name of the file containing the ExportPackages SSM command.

  ImportPackageIncludeFileParameter:
    Type: String
    Default: AEM-ImportPackage.yaml
    Description: >-
      The name of the file containing the ImportPackage SSM command.

  PromoteAuthorIncludeFileParameter:
    Type: String
    Default: AEM-PromoteAuthor.yaml
    Description: >-
      The name of the file containing the PromoteAuthor SSM command.

  ManageServiceIncludeFileParameter:
    Type: String
    Default: AEM-ManageService.yaml
    Description: >-
      The name of the file containing the ManageService SSM command.

  OfflineCompactionSnapshotFullsetIncludeFileParameter:
    Type: String
    Default: AEM-OfflineCompactionSnapshotFullset.yaml
    Description: >-
      The name of the file containing the OfflineCompactionSnapshotFullset SSM command.

  OfflineSnapshotFullsetIncludeFileParameter:
    Type: String
    Default: AEM-OfflineSnapshotFullset.yaml
    Description: >-
      The name of the file containing the OfflineSnapshotFullset SSM command.

  WaitUntilReadyIncludeFileParameter:
    Type: String
    Default: AEM-WaitUntilReady.yaml
    Description: >-
      The name of the file containing the WaitUntilReady SSM command.

  EnableCrxdeIncludeFileParameter:
    Type: String
    Default: AEM-EnableCrxde.yaml
    Description: >-
      The name of the file containing the EnableCrxde SSM command.

  DisableCrxdeIncludeFileParameter:
    Type: String
    Default: AEM-DisableCrxde.yaml
    Description: >-
      The name of the file containing the DisableCrxde SSM command.

  ListPackagesIncludeFileParameter:
    Type: String
    Default: AEM-ListPackages.yaml
    Description: >-
      The name of the file containing the ListPackages SSM command.

  RunAdhocPuppetIncludeFileParameter:
    Type: String
    Default: AEM-RunAdhocPuppet.yaml
    Description: >-
      The name of the file containing the RunAdhocPuppet SSM command.

  LiveSnapshotIncludeFileParameter:
    Type: String
    Default: AEM-LiveSnapshot.yaml
    Description: >-
      The name of the file containing the LiveSnapshot SSM command

  FlushDispatcherCacheIncludeFileParameter:
    Type: String
    Default: AEM-FlushDispatcherCache.yaml
    Description: >-
      The name of the file containing the FlushDispatcherCache SSM command

  ScheduleOfflineSnapshotIncludeFileParameter:
    Type: String
    Default: AEM-ScheduleOfflineSnapshot.yaml
    Description: >-
      The name of the file containing the ScheduleOfflineSnapshot SSM command.

  TestReadinessFullsetIncludeFileParameter:
    Type: String
    Default: AEM-TestReadinessFullset.yaml
    Description: >-
      The name of the file containing the TestReadinessFullset SSM command.

  TestReadinessConsolidatedIncludeFileParameter:
    Type: String
    Default: AEM-TestReadinessConsolidated.yaml
    Description: >-
      The name of the file containing the TestReadinessConsolidated SSM command.

Resources:
  DeployArtifact:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${DeployArtifactIncludeFileParameter}'

  DeployArtifacts:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${DeployArtifactsIncludeFileParameter}'

  ExportPackage:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${ExportPackageIncludeFileParameter}'

  ExportPackages:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${ExportPackagesIncludeFileParameter}'

  ImportPackage:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${ImportPackageIncludeFileParameter}'

  PromoteAuthor:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${PromoteAuthorIncludeFileParameter}'

  ManageService:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${ManageServiceIncludeFileParameter}'

  OfflineCompactionSnapshotFullset:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${OfflineCompactionSnapshotFullsetIncludeFileParameter}'

  OfflineSnapshotFullset:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${OfflineSnapshotFullsetIncludeFileParameter}'

  WaitUntilReady:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters: !Sub '${S3BucketAndPrefixParameter}/${WaitUntilReadyIncludeFileParameter}'

  EnableCrxde:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters: !Sub '${S3BucketAndPrefixParameter}/${EnableCrxdeIncludeFileParameter}'

  DisableCrxde:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters: !Sub '${S3BucketAndPrefixParameter}/${DisableCrxdeIncludeFileParameter}'

  ListPackages:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters: !Sub '${S3BucketAndPrefixParameter}/${ListPackagesIncludeFileParameter}'

  RunAdhocPuppet:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters: !Sub '${S3BucketAndPrefixParameter}/${RunAdhocPuppetIncludeFileParameter}'

  LiveSnapshot:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters: !Sub '${S3BucketAndPrefixParameter}/${LiveSnapshotIncludeFileParameter}'

  FlushDispatcherCache:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters: !Sub '${S3BucketAndPrefixParameter}/${FlushDispatcherCacheIncludeFileParameter}'

  ScheduleOfflineSnapshot:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${ScheduleOfflineSnapshotIncludeFileParameter}'

  TestReadinessFullset:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${TestReadinessFullsetIncludeFileParameter}'

  TestReadinessConsolidated:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub '${S3BucketAndPrefixParameter}/${TestReadinessConsolidatedIncludeFileParameter}'

Outputs:
  DeployArtifact:
    Description: Document name for Deploy Artifact
    Value: !Ref DeployArtifact

  DeployArtifacts:
    Description: Document name for Deploy Artifacts
    Value: !Ref DeployArtifacts

  ExportPackage:
    Description: Document name for Export Package
    Value: !Ref ExportPackage

  ExportPackages:
    Description: Document name for Export Package
    Value: !Ref ExportPackages

  ImportPackage:
    Description: Document name for Import Package
    Value: !Ref ImportPackage

  PromoteAuthor:
    Description: Documention name for Promote Author
    Value: !Ref PromoteAuthor

  ManageService:
    Description: Document name for Manage Service
    Value: !Ref ManageService

  OfflineCompactionSnapshotFullset:
    Description: Document name for Offline Compaction Snapshot Fullset
    Value: !Ref OfflineCompactionSnapshotFullset

  OfflineSnapshotFullset:
    Description: Document name for Offline Snapshot Fullset
    Value: !Ref OfflineSnapshotFullset

  WaitUntilReady:
    Description: Document name for Wait Until Ready
    Value: !Ref WaitUntilReady

  EnableCrxde:
    Description: Document name for Enable Crxde
    Value: !Ref EnableCrxde

  DisableCrxde:
    Description: Document name for Disable Crxde
    Value: !Ref DisableCrxde

  ListPackages:
    Description: Document name for List Packages
    Value: !Ref ListPackages

  RunAdhocPuppet:
    Description: Document name for Run Adhoc Puppet
    Value: !Ref RunAdhocPuppet

  LiveSnapshot:
    Description: Document name for Live Snapshot
    Value: !Ref LiveSnapshot

  FlushDispatcherCache:
    Description: Document name for FlushDispatcherCache
    Value: !Ref FlushDispatcherCache

  ScheduleOfflineSnapshot:
    Description: Documention name for Test Readiness Fullset
    Value: !Ref ScheduleOfflineSnapshot

  TestReadinessFullset:
    Description: Documention name for Test Readiness Fullset
    Value: !Ref TestReadinessFullset

  TestReadinessConsolidated:
    Description: Documention name for Test Readiness Consolidated
    Value: !Ref TestReadinessConsolidated
