AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Author Publish Dispatcher

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  AuthorPublishDispatcherImageParameter:
    Type: AWS::EC2::Image::Id
    Description: AMI Id used for the Host

  AuthorPublishDispatcherImageRootDevice:
    Type: String
    Description: The root device name for the Author Publish Dispatcher Image Id
    Default: /dev/sda1

  AuthorPublishDispatcherInstanceTypeParameter:
    Type: String
    Description: The Author Publish Dispatcher Instance Type

  AuthorPublishDispatcherInstanceProfileParameter:
    Type: String
    Description: The Author Publish Dispatcher Instance Profile (Use this OR AuthorPublishDispatcherInstanceProfileStackPrefixParameter)

  AuthorPublishDispatcherInstanceProfileStackPrefixParameter:
    Type: String
    Description: The Author Publish Dispatcher Instance Profile Stack Prefix  (Use this OR AuthorPublishDispatcherInstanceProfileParameter)

  AuthorPublishDispatcherSecurityGroupParameter:
    Type: String
    Description: The Author Publish Dispatcher Security Group Id (Use this OR AuthorPublishDispatcherSecurityGroupStackPrefixParameter)

  AuthorPublishDispatcherSecurityGroupStackPrefixParameter:
    Type: String
    Description: The Author Publish Dispatcher Security Group Id Stack Prefix (Use this OR AuthorPublishDispatcherSecurityGroupParameter)

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  AuthorPublishDispatcherRootVolSizeParameter:
    Type: Number
    Description: Author Publish Dispatcher Instances Root EBS Volume Size

  AuthorPublishDispatcherDataVolSizeParameter:
    Type: Number
    Description: Author Publish Dispatcher Instances Data EBS Volume Size

  AuthorPublishDispatcherSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Ids the Host Will be Launched into

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

  AssociatePublicIpAddressParameter:
    Type: String
    Description: Add Public IP Address to instance

  Route53HostedZoneNameParameter:
    Type: String
    Description: Route53 Hosted Zone Name the Record Set will be Created in

  AuthorPublishDispatcherDNSRecordSetNamePrefixParameter:
    Type: String
    Description: Author Publish Dispatcher DNS Record Set Prefix Name

  AuthorPublishDispatcherDNSRecordSetNameSuffixParameter:
    Type: String
    Description: Author Publish Dispatcher DNS Record Set Suffix Name

  DNSRecordSetTTL:
    Type: String
    Description: Record Set TTL value

Conditions:

  HasNotInstanceProfileParameterCondition:
    Fn::Equals:
      - Ref: AuthorPublishDispatcherInstanceProfileParameter
      - ""

  HasNotSecurityGroupParameterCondition:
    Fn::Equals:
      - Ref: AuthorPublishDispatcherSecurityGroupParameter
      - ""

  HasNotSubnetParameterCondition:
    Fn::Equals:
      - Ref: AuthorPublishDispatcherSubnet
      - ""

Resources:


  AuthorPublishDispatcherInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName:
          Ref: AuthorPublishDispatcherImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdc
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::If:
          - HasNotInstanceProfileParameterCondition
          - Fn::ImportValue: !Sub ${AuthorPublishDispatcherInstanceProfileStackPrefixParameter}-AuthorPublishDispatcherInstanceProfile
          - Ref: AuthorPublishDispatcherInstanceProfileParameter
      ImageId:
        Ref: AuthorPublishDispatcherImageParameter
      InstanceType:
        Ref: AuthorPublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      NetworkInterfaces:
      - AssociatePublicIpAddress:
          Ref: AssociatePublicIpAddressParameter
        DeviceIndex: '0'
        GroupSet:
        - Ref: InboundFromBastionHostSecurityGroupParameter
        - Fn::If:
            - HasNotSecurityGroupParameterCondition
            - Fn::ImportValue: !Sub ${AuthorPublishDispatcherSecurityGroupStackPrefixParameter}-AuthorPublishDispatcherSecurityGroup
            - Ref: AuthorPublishDispatcherSecurityGroupParameter
        SubnetId:
          Fn::If:
            - HasNotSubnetParameterCondition
            - Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-AuthorDispatcherSubnetA
            - Ref: AuthorPublishDispatcherSubnet
      Tags:
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
      - Key: Name
        Value: AuthorPublishDispatcher
      - Key: Component
        Value: author-publish-dispatcher
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${ComputeStackPrefixParameter} author-publish-dispatcher\
            \ ${AemAwsStackProvisionerVersionParameter}\n"

  AuthorPublishDispatcherRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName:
        Ref: Route53HostedZoneNameParameter
      Name:
        Fn::Sub: ${AuthorPublishDispatcherDNSRecordSetNamePrefixParameter}${ComputeStackPrefixParameter}${AuthorPublishDispatcherDNSRecordSetNameSuffixParameter}.${Route53HostedZoneNameParameter}
      ResourceRecords:
      - Fn::GetAtt: [AuthorPublishDispatcherInstance, PrivateIp]
      TTL:
        Ref: DNSRecordSetTTL
      Type: A
