AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Publish Dispatcher

Parameters:

  InstanceProfileStackPrefixParameter:
    Type: String
    Description: The AEM Stack Instance Profile Stack Prefix

  SecurityGroupStackPrefixParameter:
    Type: String
    Description: The AEM Stack Security Groups Resources Stack Prefix

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  PublishDispatcherLoadBalancerHealthCheckTargetParameter:
    Type: String
    Description: AEM Publish Dispatcher ELB Health Check Target

  PublishDispatcherLoadBalancerSchemeParameter:
    Type: String
    Description: AEM Publish Dispatcher ELB Scheme

  PublishDispatcherImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Publish Dispatcher Image Id

  PublishDispatcherASGCPUScalingParameters:
    Type: CommaDelimitedList
    Description: The ASG CPU scalang parameters that extra Publish Dispatcher instances are scaled up/down at

  PublishDispatcherImageRootDevice:
    Type: String
    Description: The root device name for the Publish Dispatcher Image Id
    Default: /dev/sda1

  PublishDispatcherInstanceTypeParameter:
    Type: String
    Description: The Publish Dispatcher Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  PublishDispatcherASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Publish Dispatcher Availability Zone List

  PublishDispatcherASGMaxSizeParameter:
    Type: String
    Description: The Publish Dispatcher Auto Scaling Group Maximum Size

  PublishDispatcherASGMinSizeParameter:
    Type: String
    Description: The Publish Dispatcher Auto Scaling Group Minimum Size

  PublishDispatcherASGDesiredCapacityParameter:
    Type: String
    Description: The Publish Dispatcher Auto Scaling Group Desired Capacity

  PublishDispatcherRootVolSizeParameter:
    Type: Number
    Description: PublishDispatcher Instances Root EBS Volume Size

  PublishDispatcherDataVolSizeParameter:
    Type: Number
    Description: PublishDispatcher Instances Root EBS Volume Size

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

Resources:

  PublishDispatcherLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        Target:
          Ref: PublishDispatcherLoadBalancerHealthCheckTargetParameter
        HealthyThreshold: '2'
        UnhealthyThreshold: '10'
        Interval: '30'
        Timeout: '5'
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      - LoadBalancerPort: '443'
        Protocol: HTTPS
        InstancePort: '443'
        InstanceProtocol: HTTPS
        SSLCertificateId: 'arn:aws:acm:ap-southeast-2:918473058104:certificate/3bf6d041-025c-4b7f-a30c-c519ee63c7e0'
          # Fn::ImportValue: !Sub ${ComputeStackPrefixParameter}-PrvWildcardCertificateARN
      Scheme:
        Ref: PublishDispatcherLoadBalancerSchemeParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupStackPrefixParameter}-PublishDispatcherELBSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      Subnets:
        - Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-PublishDispatcherELBSubnetA
        - Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-PublishDispatcherELBSubnetB
      Tags:
      - Key: Name
        Value: AEM Publish Dispatcher Load Balancer
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter

  PublishDispatcherLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName: !Ref PublishDispatcherImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDispatcherRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${InstanceProfileStackPrefixParameter}-PublishDispatcherInstanceProfile
      ImageId:
        Ref: PublishDispatcherImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupStackPrefixParameter}-PublishDispatcherSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} publish-dispatcher ${AemAwsStackProvisionerVersionParameter}\n"

  PublishDispatcherScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PublishDispatcherAutoScalingGroup
      Cooldown: 480
      ScalingAdjustment: 1

  PublishDispatcherScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PublishDispatcherAutoScalingGroup
      Cooldown: 480
      ScalingAdjustment: -1

  PublishDispatcherCPUHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Scale up if CPU Avg > X % for X minutes"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: !Select [1, !Ref PublishDispatcherASGCPUScalingParameters]
      EvaluationPeriods: !Select [2, !Ref PublishDispatcherASGCPUScalingParameters]
      Threshold: !Select [0, !Ref PublishDispatcherASGCPUScalingParameters]
      TreatMissingData: breaching
      AlarmActions:
      - Ref: PublishDispatcherScaleUpPolicy
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref PublishDispatcherAutoScalingGroup
      ComparisonOperator: GreaterThanThreshold            

  PublishDispatcherCPULowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Scale down if CPU Avg < X % for X minutes"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: !Select [3, !Ref PublishDispatcherASGCPUScalingParameters]
      EvaluationPeriods: !Select [4, !Ref PublishDispatcherASGCPUScalingParameters]
      Threshold: !Select [0, !Ref PublishDispatcherASGCPUScalingParameters]
      TreatMissingData: breaching
      AlarmActions:
      - Ref: PublishDispatcherScaleDownPolicy
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref PublishDispatcherAutoScalingGroup
      ComparisonOperator: LessThanThreshold

  PublishDispatcherAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: PublishDispatcherASGAvailabilityZoneListParameter
      Cooldown: 480
      HealthCheckGracePeriod: 1200
      HealthCheckType: ELB
      LaunchConfigurationName:
        Ref: PublishDispatcherLaunchConfiguration
      LoadBalancerNames:
      - Ref: PublishDispatcherLoadBalancer
      MaxSize:
        Ref: PublishDispatcherASGMaxSizeParameter
      MinSize:
        Ref: PublishDispatcherASGMinSizeParameter
      DesiredCapacity:
        Ref: PublishDispatcherASGDesiredCapacityParameter
      NotificationConfigurations:
      - NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        TopicARN:
          Fn::ImportValue:
            Fn::Sub: ${ComputeStackPrefixParameter}-AEMASGEventTopic
      Tags:
        - Key: Name
          Value: AEM Publish Dispatcher
          PropagateAtLaunch: true
        - Key: StackPrefix
          Value:
            Ref: ComputeStackPrefixParameter
          PropagateAtLaunch: true
        - Key: Component
          Value: publish-dispatcher
          PropagateAtLaunch: true
        - Key: ApplicationDescriptorUrl
          Value: PLACEHOLDER
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        Fn::Split:
          - ","
          - Fn::ImportValue:
             !Sub ${NetworkStackPrefixParameter}-PublishDispatcherSubnetList
      MetricsCollection:
        - Granularity: "1Minute"
          Metrics:
            - "GroupMinSize"
            - "GroupMaxSize"
            - "GroupDesiredCapacity"
            - "GroupInServiceInstances"
            - "GroupPendingInstances"
            - "GroupStandbyInstances"
            - "GroupTerminatingInstances"
            - "GroupTotalInstances"

Outputs:

  PublishDispatcherLoadBalancer:
    Value:
      Ref: PublishDispatcherLoadBalancer
    Export:
      Name: !Sub ${ComputeStackPrefixParameter}-PublishDispatcherLoadBalancer
    Description: The Publish Dispatcher Load Balancer

  PublishDispatcherLoadBalancerDNSName:
    Value:
      Fn::GetAtt: [PublishDispatcherLoadBalancer, DNSName]
    Export:
      Name: !Sub ${ComputeStackPrefixParameter}-PublishDispatcherLoadBalancerDNSName
    Description: The Publish Dispatcher Load Balancer DNSName

  PublishDispatcherLaunchConfiguration:
    Value:
      Ref: PublishDispatcherLaunchConfiguration
    Description: The Publish Dispatcher Launch Configuration

  PublishDispatcherAutoScalingGroup:
    Value:
      Ref: PublishDispatcherAutoScalingGroup
    Export:
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-PublishDispatcherAutoScalingGroup
    Description: The Publish Dispatcher Auto Scaling Group
