AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Publish Dispatcher

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  SSLCertificateARNParameter:
    Type: String
    Description: The ARN for SSL Certificate

  PublishDispatcherLoadBalancerHealthCheckTargetParameter:
    Type: String
    Description: AEM Publish Dispatcher ELB Health Check Target

  PublishDispatcherLoadBalancerSchemeParameter:
    Type: String
    Description: AEM Publish Dispatcher ELB Scheme

  PublishDispatcherELBSubnetListParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Publish Dispatcher ELB Subnets

  PublishDispatcherInstanceProfileParameter:
    Type: String
    Description: The Publish Dispatcher Instance Profile

  PublishDispatcherImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Publish Dispatcher Image Id

  PublishDispatcherInstanceTypeParameter:
    Type: String
    Description: The Publish Dispatcher Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  PublishDispatcherASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Publish Dispatcher Availability Zone List

  PublishDispatcherASGSubnetListParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Publish Dispatcher Subnets

  PublishDispatcherASGMaxSizeParameter:
    Type: String
    Description: The Publish Dispatcher Auto Scaling Group Maximum Size

  PublishDispatcherASGMinSizeParameter:
    Type: String
    Description: The Publish Dispatcher Auto Scaling Group Minimum Size

  PublishDispatcherASGCPUScalingParameter:
    Type: String
    Description: The CPU threshold that extra Publish Dispatcher instances are scaled up at

  PublishDispatcherRootVolSizeParameter:
    Type: Number
    Description: PublishDispatcher Instances Root EBS Volume Size

  PublishDispatcherDataVolSizeParameter:
    Type: Number
    Description: PublishDispatcher Instances Root EBS Volume Size

  PublishDispatcherTagNameParameter:
    Type: String
    Description: The Publish Dispatcher Name Tag

  PublishDispatcherLoadBalancerTagNameParameter:
    Type: String
    Description: The Publish Dispatcher Load Balancer Name Tag

  RolesStackNameParameter:
    Type: String
    Description: The AEM Roles Stack Name

  SecurityGroupsStackNameParameter:
    Type: String
    Description: The AEM Security Groups Stack Name

  MessagingStackNameParameter:
    Type: String
    Description: The AEM Messaging Stack Name

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

Resources:


  PublishDispatcherLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        Target:
          Ref: PublishDispatcherLoadBalancerHealthCheckTargetParameter
        HealthyThreshold: '2'
        UnhealthyThreshold: '10'
        Interval: '30'
        Timeout: '5'
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      - LoadBalancerPort: '443'
        Protocol: HTTPS
        InstancePort: '443'
        InstanceProtocol: HTTPS
        SSLCertificateId:
          Ref: SSLCertificateARNParameter
      Scheme:
        Ref: PublishDispatcherLoadBalancerSchemeParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupsStackNameParameter}-PublishDispatcherELBSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      Subnets:
        Ref: PublishDispatcherELBSubnetListParameter
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${PublishDispatcherLoadBalancerTagNameParameter}
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter

  PublishDispatcherLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDispatcherRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Ref: PublishDispatcherInstanceProfileParameter
      ImageId:
        Ref: PublishDispatcherImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupsStackNameParameter}-PublishDispatcherSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} publish-dispatcher ${AemAwsStackProvisionerVersionParameter}\n"

  PublishDispatcherScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PublishDispatcherAutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: 1

  PublishDispatcherScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref PublishDispatcherAutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: -1
  
  PublishDispatcherCPUHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Scale up if CPU Avg > $PublishDispatcherASGCPUScalingParameter % for 10 minutes"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 120
      EvaluationPeriods: 5
      Threshold: !Ref PublishDispatcherASGCPUScalingParameter
      AlarmActions:
      - Ref: PublishDispatcherScaleUpPolicy
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref PublishDispatcherAutoScalingGroup
      ComparisonOperator: GreaterThanThreshold

  PublishDispatcherCPULowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Scale down if CPU Avg < $PublishDispatcherASGCPUScalingParameter % for 10 minutes"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 120
      EvaluationPeriods: 5
      Threshold: !Ref PublishDispatcherASGCPUScalingParameter
      AlarmActions:
      - Ref: PublishDispatcherScaleDownPolicy
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref PublishDispatcherAutoScalingGroup
      ComparisonOperator: LessThanThreshold

  PublishDispatcherAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: PublishDispatcherASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 1200
      HealthCheckType: ELB
      LaunchConfigurationName:
        Ref: PublishDispatcherLaunchConfiguration
      LoadBalancerNames:
      - Ref: PublishDispatcherLoadBalancer
      MaxSize:
        Ref: PublishDispatcherASGMaxSizeParameter
      MinSize:
        Ref: PublishDispatcherASGMinSizeParameter
      NotificationConfigurations:
      - NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        TopicARN:
          Fn::ImportValue:
            Fn::Sub: ${MessagingStackNameParameter}-AEMASGEventTopic
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${PublishDispatcherTagNameParameter}
        PropagateAtLaunch: true
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
        PropagateAtLaunch: true
      - Key: Component
        Value: publish-dispatcher
        PropagateAtLaunch: true
      - Key: ApplicationDescriptorUrl
        Value: PLACEHOLDER
        PropagateAtLaunch: true
      VPCZoneIdentifier:
        Ref: PublishDispatcherASGSubnetListParameter

Outputs:

  PublishDispatcherLoadBalancer:
    Value:
      Ref: PublishDispatcherLoadBalancer
    Description: The Publish Dispatcher Load Balancer

  PublishDispatcherLoadBalancerDNSName:
    Value:
      Fn::GetAtt: [PublishDispatcherLoadBalancer, DNSName]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LoadBalancerDNSName
    Description: The Publish Dispatcher Load Balancer DNSName

  PublishDispatcherLaunchConfiguration:
    Value:
      Ref: PublishDispatcherLaunchConfiguration
    Description: The Publish Dispatcher Launch Configuration

  PublishDispatcherAutoScalingGroup:
    Value:
      Ref: PublishDispatcherAutoScalingGroup
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-PublishDispatcherAutoScalingGroup
    Description: The Publish Dispatcher Auto Scaling Group
