AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Publish Dispatcher

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  PublishDispatcherLoadBalancerHealthCheckTargetParameter:
    Type: String
    Description: AEM Publish Dispatcher ELB Health Check Target

  PublishDispatcherLoadBalancerSchemeParameter:
    Type: String
    Description: AEM Publish Dispatcher ELB Scheme

  PublishDispatcherImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Publish Dispatcher Image Id

  PublishDispatcherImageRootDevice:
    Type: String
    Description: The root device name for the Publish Dispatcher Image Id
    Default: /dev/sda1

  PublishDispatcherInstanceTypeParameter:
    Type: String
    Description: The Publish Dispatcher Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  PublishDispatcherASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Publish Dispatcher Availability Zone List

  PublishDispatcherASGMaxSizeParameter:
    Type: String
    Description: The Publish Dispatcher Auto Scaling Group Maximum Size

  PublishDispatcherASGMinSizeParameter:
    Type: String
    Description: The Publish Dispatcher Auto Scaling Group Minimum Size

  PublishDispatcherRootVolSizeParameter:
    Type: Number
    Description: PublishDispatcher Instances Root EBS Volume Size

  PublishDispatcherDataVolSizeParameter:
    Type: Number
    Description: PublishDispatcher Instances Root EBS Volume Size

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

Resources:

  PublishDispatcherLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        Target:
          Ref: PublishDispatcherLoadBalancerHealthCheckTargetParameter
        HealthyThreshold: '2'
        UnhealthyThreshold: '10'
        Interval: '30'
        Timeout: '5'
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      - LoadBalancerPort: '443'
        Protocol: HTTPS
        InstancePort: '443'
        InstanceProtocol: HTTPS
        SSLCertificateId:
          Fn::ImportValue: !Sub ${ComputeStackPrefixParameter}-WildcardCertificateARN
      Scheme:
        Ref: PublishDispatcherLoadBalancerSchemeParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${ComputeStackPrefixParameter}-PublishDispatcherELBSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      Subnets:
        - Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-PublishDispatcherELBSubnetA
        - Fn::ImportValue: !Sub ${NetworkStackPrefixParameter}-PublishDispatcherELBSubnetB
      Tags:
      - Key: Name
        Value: AEM Publish Dispatcher Load Balancer
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter

  PublishDispatcherLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName: !Ref PublishDispatcherImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDispatcherRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue: !Sub ${ComputeStackPrefixParameter}-PublishDispatcherInstanceProfile
      ImageId:
        Ref: PublishDispatcherImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${ComputeStackPrefixParameter}-PublishDispatcherSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} publish-dispatcher ${AemAwsStackProvisionerVersionParameter}\n"
  PublishDispatcherAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: PublishDispatcherASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 900
      HealthCheckType: ELB
      LaunchConfigurationName:
        Ref: PublishDispatcherLaunchConfiguration
      LoadBalancerNames:
      - Ref: PublishDispatcherLoadBalancer
      MaxSize:
        Ref: PublishDispatcherASGMaxSizeParameter
      MinSize:
        Ref: PublishDispatcherASGMinSizeParameter
      NotificationConfigurations:
      - NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        TopicARN:
          Fn::ImportValue:
            Fn::Sub: ${ComputeStackPrefixParameter}-AEMASGEventTopic
      Tags:
        - Key: Name
          Value: AEM Publish Dispatcher
          PropagateAtLaunch: true
        - Key: StackPrefix
          Value:
            Ref: ComputeStackPrefixParameter
          PropagateAtLaunch: true
        - Key: Component
          Value: publish-dispatcher
          PropagateAtLaunch: true
        - Key: ApplicationDescriptorUrl
          Value: PLACEHOLDER
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        - Fn::ImportValue:
            !Sub ${NetworkStackPrefixParameter}-PublishDispatcherSubnetA
        - Fn::ImportValue:
            !Sub ${NetworkStackPrefixParameter}-PublishDispatcherSubnetB

Outputs:

  PublishDispatcherLoadBalancer:
    Value:
      Ref: PublishDispatcherLoadBalancer
    Description: The Publish Dispatcher Load Balancer

  PublishDispatcherLoadBalancerDNSName:
    Value:
      Fn::GetAtt: [PublishDispatcherLoadBalancer, DNSName]
    Export:
      Name:
        Fn::Sub : ${ComputeStackPrefixParameter}-PublishDispatcherLoadBalancerDNSName
    Description: The Publish Dispatcher Load Balancer DNSName

  PublishDispatcherLaunchConfiguration:
    Value:
      Ref: PublishDispatcherLaunchConfiguration
    Description: The Publish Dispatcher Launch Configuration

  PublishDispatcherAutoScalingGroup:
    Value:
      Ref: PublishDispatcherAutoScalingGroup
    Description: The Publish Dispatcher Auto Scaling Group
