AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  CreatePrivateHostedZoneCondition:
    Fn::Equals:
    - Ref: CreatePrivateHostedZone
    - 'true'
  CreateS3BucketCondition:
    Fn::Equals:
    - Ref: CreateS3Bucket
    - 'true'
Description: AWS resources stack for AEM Stack Builder/Manager
Parameters:
  AemEnvS3BucketName:
    Description: Name of the S3 Bucket for storing AEM environment states
    Type: String
  CreatePrivateHostedZone:
    Description: Toggle creating a Private HostedZone in Route53
    Type: String
  CreateS3Bucket:
    Description: Toggle creating the S3 bucket
    Type: String
  PrivateHostedZoneName:
    Description: Name of the Private HostedZone domain, fully qualified domain with
      trailing dot (.)
    Type: String
  VPCId:
    Description: VPCId to associate with the Private HostedZone
    Type: String
  VPCRegion:
    Description: VPC region to associate with the Private HostedZone
    Type: String
Resources:
  AemEnvS3Bucket:
    Condition: CreateS3BucketCondition
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      BucketName:
        Ref: AemEnvS3BucketName
    Type: AWS::S3::Bucket
  PrivateHostedZone:
    Condition: CreatePrivateHostedZoneCondition
    Properties:
      Name:
        Ref: PrivateHostedZoneName
      VPCs:
      - VPCId:
          Ref: VPCId
        VPCRegion:
          Ref: VPCRegion
    Type: AWS::Route53::HostedZone
