---
schemaVersion: '2.0'
description: >-
  Reconfigure an existing AEM installation.
parameters:
  aemBase:
    description: >-
      (Required) AEM installation base path.
    type: String
  aemHealthcheckSource:
    description: >-
      (Optional) AEM Healthcheck source path.
    type: String
    default: ''
  aemHealthcheckVersion:
    description: >-
      (Required) AEM Healthcheck version.
    type: String
  aemID:
    description: >-
      (Required) AEM ID.
    type: String
  aemKeystorePassword:
    description: >-
      (Required) AEM Keystore Password.
    type: String
  aemKeystorePath:
    description: >-
      (Optional) Filesystem path to the AEM Keystore.
    type: String
    default: ''
  aemSslPort:
    description: >-
      (Required) AEM HTTPS listening port.
    type: String
  certBaseUrl:
    description: >-
      (Required) Filesystem / S3 Path or URL to aem.cert & aem.key.
    type: String
  force:
    description: >-
      (Optional) Force reconfiguration. If this option is set to true it will delete
      any existing configuration. The default value is "true".
    type: String
    default: 'true'
  executionTimeout:
    description: >-
      (Optional) The time in seconds for a command to be completed before it is
      considered to have failed. Default is 3600 (1 hour). Maximum is 28800 (8
      hours).
    type: String
    allowedPattern: ([1-9][0-9]{0,3})|(1[0-9]{1,4})|(2[0-7][0-9]{1,3})|(28[0-7][0-9]{1,2})|(28800)
    default: '7200'
mainSteps:
  - action: aws:runShellScript
    name: runShellScript
    inputs:
      runCommand:
        - '. /etc/profile'
        - 'while [ ! -f /opt/shinesolutions/aem-aws-stack-builder/stack-init-completed ]; do sleep 15; echo "Waiting for component initialisation to complete..."; done'
        - '/opt/shinesolutions/aem-tools/reconfigure-aem.sh {{aemID}} {{aemBase}} {{aemHealthcheckSource}} {{aemHealthcheckVersion}} {{aemKeystorePassword}} {{aemKeystorePath}} {{certBaseUrl}} {{aemSslPort}} {{force}}'
      timeoutSeconds: '{{ executionTimeout }}'
      workingDirectory: /tmp
