AWSTemplateFormatVersion: '2010-09-09'
Description: Create Instance Profiles for AEM Stack
Outputs:
  AEMStackManagerSnapshotLambdaServiceRoleArn:
    Description: The Stack Manager Lambda Service Role ARN
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-StackManagerSnapshotLambdaServiceRoleArn
    Value:
      Ref: AEMStackManagerSnapshotLambdaServiceRoleArnParameter
  AEMStackManagerSnapshotLambdaServiceRoleName:
    Description: AEM StackManager Snapshot Lambda Service Role Name
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-StackManagerSnapshotLambdaServiceRoleName
    Value:
      Ref: AEMStackManagerSnapshotLambdaServiceRoleNameParameter
  AuthorDispatcherInstanceProfile:
    Description: The Author Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorDispatcherInstanceProfile
    Value:
      Ref: AuthorDispatcherInstanceProfileParameter
  AuthorInstanceProfile:
    Description: The Author Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorInstanceProfile
    Value:
      Ref: AuthorInstanceProfileParameter
  ChaosMonkeyInstanceProfile:
    Description: The Chaos Monkey Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-ChaosMonkeyInstanceProfile
    Value:
      Ref: ChaosMonkeyInstanceProfileParameter
  OrchestratorInstanceProfile:
    Description: The Orchestrator Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-OrchestratorInstanceProfile
    Value:
      Ref: OrchestratorInstanceProfileParameter
  PublishDispatcherInstanceProfile:
    Description: The Publish Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishDispatcherInstanceProfile
    Value:
      Ref: PublishDispatcherInstanceProfileParameter
  PublishInstanceProfile:
    Description: The Publish Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishInstanceProfile
    Value:
      Ref: PublishInstanceProfileParameter
Parameters:
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
  AEMStackManagerSnapshotLambdaServiceRoleArnParameter:
    Description: The Stack Manager Lambda Service Role ARN
    Type: String
  AEMStackManagerSnapshotLambdaServiceRoleNameParameter:
    Description: AEM StackManager Snapshot Lambda Service Role Name
    Type: String
  AuthorDispatcherInstanceProfileParameter:
    Description: The Author Dispatcher Instance Profile
    Type: String
  AuthorInstanceProfileParameter:
    Description: The Author Instance Profile
    Type: String
  ChaosMonkeyInstanceProfileParameter:
    Description: The Chaos Monkey Instance Profile
    Type: String
  OrchestratorInstanceProfileParameter:
    Description: The Orchestrator Instance Profile
    Type: String
  PublishDispatcherInstanceProfileParameter:
    Description: The Publish Dispatcher Instance Profile
    Type: String
  PublishInstanceProfileParameter:
    Description: The Publish Instance Profile
    Type: String
Resources:
  DummyParameter:
    Properties:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-DummyParameter
      Description: Dummy Parameter to allow stack to work.
      Type: String
      Value:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-DummyParameter
    Type: "AWS::SSM::Parameter"
