AWSTemplateFormatVersion: '2010-09-09'
Description: Create Instance Profiles for AEM Stack
Outputs:
  AEMStackManagerSnapshotLambdaServiceRoleArn:
    Description: The Stack Manager Lambda Service Role ARN
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-StackManagerSnapshotLambdaServiceRoleArn
    Value:
      Fn::GetAtt: AEMStackManagerSnapshotLambdaServiceRole.Arn
  AEMStackManagerSnapshotLambdaServiceRoleName:
    Description: AEM StackManager Snapshot Lambda Service Role Name
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-StackManagerSnapshotLambdaServiceRoleName
    Value:
      Ref: AEMStackManagerSnapshotLambdaServiceRole
  AuthorDispatcherInstanceProfile:
    Description: The Author Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorDispatcherInstanceProfile
    Value:
      Ref: AuthorDispatcherInstanceProfile
  AuthorInstanceProfile:
    Description: The Author Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorInstanceProfile
    Value:
      Ref: AuthorInstanceProfile
  ChaosMonkeyInstanceProfile:
    Description: The Chaos Monkey Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-ChaosMonkeyInstanceProfile
    Value:
      Ref: ChaosMonkeyInstanceProfile
  OrchestratorInstanceProfile:
    Description: The Orchestrator Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-OrchestratorInstanceProfile
    Value:
      Ref: OrchestratorInstanceProfile
  PublishDispatcherInstanceProfile:
    Description: The Publish Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishDispatcherInstanceProfile
    Value:
      Ref: PublishDispatcherInstanceProfile
  PublishInstanceProfile:
    Description: The Publish Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishInstanceProfile
    Value:
      Ref: PublishInstanceProfile
Parameters:
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
Resources:
  DummyGroup:
    Properties:
      GroupDescription: Dummy security group to allow stack to work.
      VpcId:
        Ref: VPCId
    Type: AWS::EC2::SecurityGroup 
