AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  UseAuthorDataVolSnapshotCondition:
    Fn::Equals:
    - Ref: UseAuthorDataVolSnapshotParameter
    - true
Description: Create the Compute resources for the AEM Author
Outputs:
  AuthorLoadBalancer:
    Description: The Author Load Balancer
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorLoadBalancer
    Value:
      Ref: AuthorLoadBalancer
  AuthorLoadBalancerDNSName:
    Description: The Author Load Balancer
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorLoadBalancerDNSName
    Value:
      Fn::GetAtt:
      - AuthorLoadBalancer
      - DNSName
  AuthorPrimaryInstance:
    Description: The Author Primary Instance
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorPrimaryInstance
    Value:
      Ref: AuthorPrimaryInstance
  AuthorStandbyInstance:
    Description: The Author Standby Instance
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorStandbyInstance
    Value:
      Ref: AuthorStandbyInstance
  AuthorSyncDelayAlarm:
    Description: The Author Sync Delay Alarm
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorSyncDelayAlarm
    Value:
      Ref: AuthorSyncDelayAlarm
Parameters:
  AemAwsStackProvisionerVersionParameter:
    Description: AEM AWS Stack Provisioner version number
    Type: String
  AuthorDataVolSizeParameter:
    Description: Author Instances Data EBS Volume Size
    Type: Number
  AuthorDataVolSnapshotParameter:
    Description: The Author Data Volume Snapshot Id
    Type: String
  AuthorImageParameter:
    Description: The Author Image Id
    Type: AWS::EC2::Image::Id
  AuthorImageRootDevice:
    Default: /dev/sda1
    Description: The root device name for the Author Image Id
    Type: String
  AuthorImageDataDevice:
    Default: /dev/sdb
    Description: The data device name for the Author Image Id
    Type: String
  AuthorInstanceTypeParameter:
    Description: The Author Instance Type
    Type: String
  AuthorLoadBalancerHealthCheckTargetParameter:
    Description: AEM Author ELB Health Check Target
    Type: String
  AuthorRootVolSizeParameter:
    Description: Author Instances Root EBS Volume Size
    Type: Number
  ComputeKeyPairNameParameter:
    Description: The Compute Resources Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  ELBCipherSuiteParameter:
    Description: ELB Cipher Suite Policy
    Type: String
  InboundFromBastionHostSecurityGroupParameter:
    Description: Inbound Bound from Bastion Host Security Group Id
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  NetworkStackPrefixParameter:
    Description: The AEM Stack Network Resources Stack Prefix
    Type: String
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
  UseAuthorDataVolSnapshotParameter:
    AllowedValues:
    - true
    - false
    Description: Whether to use the Author Snapshot Data Volume.
    Type: String
Resources:
  AuthorLoadBalancer:
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        HealthyThreshold: '2'
        Interval: '30'
        Target:
          Ref: AuthorLoadBalancerHealthCheckTargetParameter
        Timeout: '5'
        UnhealthyThreshold: '2'
      Instances:
      - Ref: AuthorPrimaryInstance
      - Ref: AuthorStandbyInstance
      Listeners:
      - InstancePort: '4502'
        LoadBalancerPort: '80'
        Protocol: HTTP
      - InstancePort: '5432'
        InstanceProtocol: HTTPS
        LoadBalancerPort: '443'
        Protocol: HTTPS
        SSLCertificateId:
          Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-SSLCertificateARN
        PolicyNames:
        - Ref: ELBCipherSuiteParameter
      Scheme: internal
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorELBSecurityGroup
      Subnets:
        Fn::Split:
        - ','
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackPrefixParameter}-AuthorELBSubnetList
      Tags:
      - Key: Name
        Value: AEM Author Load Balancer
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
      - Key: Project
        Value: Open Source AEM Platform
    Type: AWS::ElasticLoadBalancing::LoadBalancer
  AuthorPrimaryInstance:
    Properties:
      BlockDeviceMappings:
      - DeviceName:
          Ref: AuthorImageRootDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted: true
          VolumeSize:
            Ref: AuthorRootVolSizeParameter
          VolumeType: gp2
      - DeviceName:
          Ref: AuthorImageDataDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted: true
          SnapshotId:
            Fn::If:
            - UseAuthorDataVolSnapshotCondition
            - Ref: AuthorDataVolSnapshotParameter
            - Ref: AWS::NoValue
          VolumeSize:
            Ref: AuthorDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorInstanceProfile
      ImageId:
        Ref: AuthorImageParameter
      InstanceType:
        Ref: AuthorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroupIds:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: ${NetworkStackPrefixParameter}-AuthorPrimarySubnet
      Tags:
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
      - Key: Name
        Value: AEM Author - Primary
      - Key: Component
        Value: author-primary
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${MainStackPrefixParameter} author-primary\
            \ ${AemAwsStackProvisionerVersionParameter}\n"
    Type: AWS::EC2::Instance
  AuthorStandbyInstance:
    Properties:
      BlockDeviceMappings:
      - DeviceName:
          Ref: AuthorImageRootDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted: true
          VolumeSize:
            Ref: AuthorRootVolSizeParameter
          VolumeType: gp2
      - DeviceName:
          Ref: AuthorImageDataDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted: true
          SnapshotId:
            Fn::If:
            - UseAuthorDataVolSnapshotCondition
            - Ref: AuthorDataVolSnapshotParameter
            - Ref: AWS::NoValue
          VolumeSize:
            Ref: AuthorDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorInstanceProfile
      ImageId:
        Ref: AuthorImageParameter
      InstanceType:
        Ref: AuthorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroupIds:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: ${NetworkStackPrefixParameter}-AuthorStandbySubnet
      Tags:
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
      - Key: Name
        Value: AEM Author - Standby
      - Key: Component
        Value: author-standby
      - Key: AuthorPrimaryHost
        Value:
          Fn::GetAtt:
          - AuthorPrimaryInstance
          - PrivateIp
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${MainStackPrefixParameter} author-standby\
            \ ${AemAwsStackProvisionerVersionParameter}\n"
    Type: AWS::EC2::Instance
  AuthorSyncDelayAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: Monitors the sync delay between the Author Standby and the Author Primary
      AlarmName:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorSyncDelayAlarm
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: FixedDimension
        Value:
          Fn::Sub: ${MainStackPrefixParameter}-author-standby
      - Name: PluginInstance
        Value: standby-status
      - Name: Host
        Value:
          Ref: AuthorStandbyInstance
      EvaluationPeriods: 5
      MetricName: GenericJMX.delay.seconds_since_last_success
      Namespace: collectd
      Period: 60
      Statistic: Maximum
      Threshold: 60
    Type: AWS::CloudWatch::Alarm
  MultiAuthorInstanceAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: Multiple Author Instances have Entered into Service
      AlarmName:
        Fn::Sub: ${MainStackPrefixParameter}-MultiAuthorInstanceAlarm
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: LoadBalancerName
        Value:
          Ref: AuthorLoadBalancer
      EvaluationPeriods: 1
      MetricName: HealthyHostCount
      Namespace: AWS/ELB
      OKActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      Period: 60
      Statistic: Maximum
      Threshold: 1
    Type: AWS::CloudWatch::Alarm
  NoAuthorInstanceAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: No Author Instance in Service
      AlarmName:
        Fn::Sub: ${MainStackPrefixParameter}-NoAuthorInstanceAlarm
      ComparisonOperator: LessThanOrEqualToThreshold
      Dimensions:
      - Name: LoadBalancerName
        Value:
          Ref: AuthorLoadBalancer
      EvaluationPeriods: 5
      MetricName: HealthyHostCount
      Namespace: AWS/ELB
      OKActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      Period: 60
      Statistic: Average
      Threshold: 0
    Type: AWS::CloudWatch::Alarm
