AWSTemplateFormatVersion: '2010-09-09'
Description: Create the Compute resources for the AEM Author Dispatcher
Outputs:
  AuthorDispatcherAutoScalingGroup:
    Description: The Author Dispatcher Auto Scaling Group
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorDispatcherAutoScalingGroup
    Value:
      Ref: AuthorDispatcherAutoScalingGroup
  AuthorDispatcherLaunchConfiguration:
    Description: The Author Dispatcher Launch Configuration
    Value:
      Ref: AuthorDispatcherLaunchConfiguration
  AuthorDispatcherLoadBalancer:
    Description: The Author Dispatcher Load Balancer
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorDispatcherLoadBalancer
    Value:
      Ref: AuthorDispatcherLoadBalancer
  AuthorDispatcherLoadBalancerDNSName:
    Description: The Author Dispatcher Load Balancer
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorDispatcherLoadBalancerDNSName
    Value:
      Fn::GetAtt:
      - AuthorDispatcherLoadBalancer
      - DNSName
Parameters:
  AemAwsStackProvisionerVersionParameter:
    Description: AEM AWS Stack Provisioner version number
    Type: String
  AuthorDispatcherASGAvailabilityZoneListParameter:
    Description: The Author Dispatcher Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  AuthorDispatcherASGConfigurationParameters:
    Description: The ASG configuration parameters
    Type: CommaDelimitedList
  AuthorDispatcherDataVolSizeParameter:
    Description: Author Dispatcher Instances Data EBS Volume Size
    Type: Number
  AuthorDispatcherImageParameter:
    Description: The Author Dispatcher Image Id
    Type: AWS::EC2::Image::Id
  AuthorDispatcherImageRootDevice:
    Default: /dev/sda1
    Description: The root device name for the Author Dispatcher Image Id
    Type: String
  AuthorDispatcherImageDataDevice:
    Default: /dev/sdb
    Description: The data device name for the Author Dispatcher Image Id
    Type: String
  AuthorDispatcherInstanceTypeParameter:
    Description: The Author Dispatcher Instance Type
    Type: String
  AuthorDispatcherLoadBalancerHealthCheckTargetParameter:
    Description: AEM Author Dispatcher ELB Health Check Target
    Type: String
  AuthorDispatcherRootVolSizeParameter:
    Description: Author Dispatcher Instances Root EBS Volume Size
    Type: Number
  ComputeKeyPairNameParameter:
    Description: The Compute Resources Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  ELBCipherSuiteParameter:
    Description: ELB Cipher Suite Policy
    Type: String
  InboundFromBastionHostSecurityGroupParameter:
    Description: Inbound Bound from Bastion Host Security Group Id
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  NetworkStackPrefixParameter:
    Description: The AEM Stack Network Resources Stack Prefix
    Type: String
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
Resources:
  AuthorDispatcherAutoScalingGroup:
    Properties:
      AvailabilityZones:
        Ref: AuthorDispatcherASGAvailabilityZoneListParameter
      Cooldown:
        Fn::Select:
          - 4
          - Ref: AuthorDispatcherASGConfigurationParameters
      DesiredCapacity:
        Fn::Select:
          - 2
          - Ref: AuthorDispatcherASGConfigurationParameters
      HealthCheckGracePeriod:
        Fn::Select:
          - 3
          - Ref: AuthorDispatcherASGConfigurationParameters
      HealthCheckType: ELB
      LaunchConfigurationName:
        Ref: AuthorDispatcherLaunchConfiguration
      LoadBalancerNames:
      - Ref: AuthorDispatcherLoadBalancer
      MaxSize:
        Fn::Select:
          - 0
          - Ref: AuthorDispatcherASGConfigurationParameters
      MetricsCollection:
      - Granularity: 1Minute
        Metrics:
        - GroupMinSize
        - GroupMaxSize
        - GroupDesiredCapacity
        - GroupInServiceInstances
        - GroupPendingInstances
        - GroupStandbyInstances
        - GroupTerminatingInstances
        - GroupTotalInstances
      MinSize:
        Fn::Select:
          - 1
          - Ref: AuthorDispatcherASGConfigurationParameters
      NotificationConfigurations:
      - NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        TopicARN:
          Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-AEMASGEventTopic
      Tags:
      - Key: Name
        PropagateAtLaunch: true
        Value: AEM Author Dispatcher
      - Key: StackPrefix
        PropagateAtLaunch: true
        Value:
          Ref: MainStackPrefixParameter
      - Key: Component
        PropagateAtLaunch: true
        Value: author-dispatcher
      VPCZoneIdentifier:
        Fn::Split:
        - ','
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackPrefixParameter}-AuthorDispatcherSubnetList
    Type: AWS::AutoScaling::AutoScalingGroup
  AuthorDispatcherLaunchConfiguration:
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName:
          Ref: AuthorDispatcherImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorDispatcherRootVolSizeParameter
          VolumeType: gp2
      - DeviceName:
          Ref: AuthorDispatcherImageDataDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorDispatcherDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorDispatcherInstanceProfile
      ImageId:
        Ref: AuthorDispatcherImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: AuthorDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorDispatcherSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${MainStackPrefixParameter} author-dispatcher\
            \ ${AemAwsStackProvisionerVersionParameter}\n"
    Type: AWS::AutoScaling::LaunchConfiguration
  AuthorDispatcherLoadBalancer:
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        HealthyThreshold: '2'
        Interval: '30'
        Target:
          Ref: AuthorDispatcherLoadBalancerHealthCheckTargetParameter
        Timeout: '5'
        UnhealthyThreshold: '2'
      Listeners:
      - InstancePort: '80'
        LoadBalancerPort: '80'
        Protocol: HTTP
      - InstancePort: '443'
        InstanceProtocol: HTTPS
        LoadBalancerPort: '443'
        Protocol: HTTPS
        SSLCertificateId:
          Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-SSLCertificateARN
        PolicyNames:
        - Ref: ELBCipherSuiteParameter
      Scheme: internal
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorDispatcherELBSecurityGroup
      Subnets:
        Fn::Split:
        - ','
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackPrefixParameter}-AuthorDispatcherELBSubnetList
      Tags:
      - Key: Name
        Value: AEM Author Dispatcher Load Balancer
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
    Type: AWS::ElasticLoadBalancing::LoadBalancer
  AuthorDispatcherAtLeastOneUnHealthyAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: At least one Author Dispatcher is Unhealthy
      AlarmName:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorDispatcherAtLeastOneUnHealthyAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: LoadBalancerName
        Value:
          Ref: AuthorDispatcherLoadBalancer
      EvaluationPeriods: 10
      MetricName: UnHealthyHostCount
      Namespace: AWS/ELB
      OKActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      Period: 60
      Statistic: Average
      Threshold: 1
    Type: AWS::CloudWatch::Alarm
  AuthorDispatcherMoreThanOneUnHealthyAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: More than one Author Dispatcher is Unhealthy
      AlarmName:
        Fn::Sub: ${MainStackPrefixParameter}-AuthorDispatcherMoreThanOneUnHealthyAlarm
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: LoadBalancerName
        Value:
          Ref: AuthorDispatcherLoadBalancer
      EvaluationPeriods: 1
      MetricName: UnHealthyHostCount
      Namespace: AWS/ELB
      OKActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      Period: 60
      Statistic: Average
      Threshold: 1
    Type: AWS::CloudWatch::Alarm
