AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  CreateChaosMonkeyStackCondition:
    Fn::Equals:
      - Ref: ChaosMonkeyIncludeStack
      - 'true'
Description: Overarching CF Template to Create AEM Full-Set Main Resources Stacks
Parameters:
  AemAwsStackProvisionerVersionParameter:
    Description: AEM AWS Stack Provisioner version number
    Type: String
  AuthorDNSRecordSetNameParameter:
    Description: Author DNS Record Set Name
    Type: String
  AuthorDataVolSizeParameter:
    Description: Author Instances Data EBS Volume Size
    Type: Number
  AuthorDataVolSnapshotParameter:
    Description: The Author Data Volume Snapshot Id
    Type: String
  AuthorDispatcherASGAvailabilityZoneListParameter:
    Description: The Author Dispatcher Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  AuthorDispatcherASGConfigurationParameters:
    Description: The ASG configuration parameters
    Type: List<String>
  AuthorDispatcherDNSRecordSetNameParameter:
    Description: AuthorDispatcher DNS Record Set Name
    Type: String
  AuthorDispatcherDataVolSizeParameter:
    Description: Author Dispatcher Instances Data EBS Volume Size
    Type: Number
  AuthorDispatcherImageParameter:
    Description: The Author Dispatcher Image Id
    Type: AWS::EC2::Image::Id
  AuthorDispatcherInstanceTypeParameter:
    Description: The Author Dispatcher Instance Type
    Type: String
  AuthorDispatcherLoadBalancerHealthCheckTargetParameter:
    Description: AEM Author Dispatcher ELB Health Check Target
    Type: String
  AuthorDispatcherRootVolSizeParameter:
    Description: Author Dispatcher Instances Root EBS Volume Size
    Type: Number
  AuthorImageParameter:
    Description: The Author Image Id
    Type: AWS::EC2::Image::Id
  AuthorInstanceTypeParameter:
    Description: The Author Instance Type
    Type: String
  AuthorLoadBalancerHealthCheckTargetParameter:
    Description: AEM Author ELB Health Check Target
    Type: String
  AuthorRootVolSizeParameter:
    Description: Author Instances Root EBS Volume Size
    Type: Number
  ChaosMonkeyIncludeStack:
    Default: 'true'
    Description: Creates the ChaosMonkey stack or not
    Type: String
  ChaosMonkeyASGAvailabilityZoneListParameter:
    Description: The Chaos Monkey Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  ChaosMonkeyImageParameter:
    Description: The Chaos Monkey Image Id
    Type: AWS::EC2::Image::Id
  ChaosMonkeyInstanceTypeParameter:
    Default: ''
    Description: The Chaos Monkey Instance Type
    Type: String
  ChaosMonkeyRootVolSizeParameter:
    Description: Chaos Monkey Instances Root EBS Volum Size
    Type: Number
  ComputeKeyPairNameParameter:
    Description: The Compute Resources Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  ELBCipherSuiteParameter:
    Description: ELB Cipher Suite Policy
    Type: String
  ImageDevices:
    Default: "/dev/sda1, /dev/sdb"
    Description: The device names for the Image Id
    Type: List<String>
  InboundFromBastionHostSecurityGroupParameter:
    Description: Inbound Bound from Bastion Host Security Group Id
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  NetworkStackPrefixParameter:
    Description: The AEM Stack Network Resources Stack Prefix
    Type: String
  OrchestratorASGAvailabilityZoneListParameter:
    Description: The Orchestrator Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  OrchestratorDataVolSizeParameter:
    Description: Orchestrator Instances Data EBS Volume Size
    Type: Number
  OrchestratorImageParameter:
    Description: The Orchestrator Image Id
    Type: AWS::EC2::Image::Id
  OrchestratorInstanceTypeParameter:
    Description: The Orchestrator Instance Type
    Type: String
  OrchestratorRootVolSizeParameter:
    Description: Orchestrator Instances Root EBS Volume Size
    Type: Number
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
  PublishASGConfigurationParameters:
    Description: The ASG configuration parameters
    Type: List<String>
  PublishASGAvailabilityZoneListParameter:
    Description: The Publish Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  PublishDataVolSizeParameter:
    Description: The Publish Instances Data EBS Volume Size
    Type: Number
  PublishDataVolSnapshotParameter:
    Description: The Publish Data Volume Snapshot Id
    Type: String
  PublishDispatcherASGConfigurationParameters:
    Description: The ASG configuration parameters
    Type: List<String>
  PublishDispatcherASGAvailabilityZoneListParameter:
    Description: The Publish Dispatcher Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  PublishDispatcherASGCPUScalingParameters:
    Description: The ASG CPU scalang parameters that extra Publish Dispatcher instances
      are scaled up/down at
    Type: List<Number>
  PublishDispatcherDNSRecordSetNameParameter:
    Description: PublishDispatcher DNS Record Set Name
    Type: String
  PublishDispatcherDataVolSizeParameter:
    Description: PublishDispatcher Instances Root EBS Volume Size
    Type: Number
  PublishDispatcherImageParameter:
    Description: The Publish Dispatcher Image Id
    Type: AWS::EC2::Image::Id
  PublishDispatcherInstanceTypeParameter:
    Description: The Publish Dispatcher Instance Type
    Type: String
  PublishDispatcherLoadBalancerHealthCheckTargetParameter:
    Description: AEM Publish Dispatcher ELB Health Check Target
    Type: String
  PublishDispatcherLoadBalancerSchemeParameter:
    Description: AEM Publish Dispatcher ELB Scheme
    Type: String
  PublishDispatcherRootVolSizeParameter:
    Description: PublishDispatcher Instances Root EBS Volume Size
    Type: Number
  PublishImageParameter:
    Description: The Publish Image Id
    Type: AWS::EC2::Image::Id
  PublishInstanceTypeParameter:
    Description: The Publish Instance Type
    Type: String
  PublishRootVolSizeParameter:
    Description: Publish Instances Root EBS Volume Size
    Type: Number
  Route53HostedZoneNameParameter:
    Description: Route53 Hosted Zone Name the Record Set will be Created in
    Type: String
  UseAuthorDataVolSnapshotParameter:
    AllowedValues:
    - true
    - false
    Description: Wheather to use the Author Snapshot Data Volume.
    Type: String
  UsePublishDataVolSnapshotParameter:
    AllowedValues:
    - true
    - false
    Description: Wheather to use the Publish Snapshot Data Volume.
    Type: String
Resources:
  AuthorDispatcherStack:
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter:
          Ref: AemAwsStackProvisionerVersionParameter
        AuthorDispatcherASGAvailabilityZoneListParameter:
          Fn::Join:
            - ','
            - Ref: AuthorDispatcherASGAvailabilityZoneListParameter
        AuthorDispatcherASGConfigurationParameters:
          Fn::Join:
            - ','
            - Ref: AuthorDispatcherASGConfigurationParameters
        AuthorDispatcherDataVolSizeParameter:
          Ref: AuthorDispatcherDataVolSizeParameter
        AuthorDispatcherImageParameter:
          Ref: AuthorDispatcherImageParameter
        AuthorDispatcherImageRootDevice:
          Fn::Select:
            - 0
            - Ref: ImageDevices
        AuthorDispatcherImageDataDevice:
          Fn::Select:
            - 1
            - Ref: ImageDevices
        AuthorDispatcherInstanceTypeParameter:
          Ref: AuthorDispatcherInstanceTypeParameter
        AuthorDispatcherLoadBalancerHealthCheckTargetParameter:
          Ref: AuthorDispatcherLoadBalancerHealthCheckTargetParameter
        AuthorDispatcherRootVolSizeParameter:
          Ref: AuthorDispatcherRootVolSizeParameter
        ComputeKeyPairNameParameter:
          Ref: ComputeKeyPairNameParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        ELBCipherSuiteParameter:
          Ref: ELBCipherSuiteParameter
        InboundFromBastionHostSecurityGroupParameter:
          Ref: InboundFromBastionHostSecurityGroupParameter
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        NetworkStackPrefixParameter:
          Ref: NetworkStackPrefixParameter
        PrerequisitesStackPrefixParameter:
          Ref: PrerequisitesStackPrefixParameter
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/author-dispatcher.yaml
    Type: AWS::CloudFormation::Stack
  AuthorStack:
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter:
          Ref: AemAwsStackProvisionerVersionParameter
        AuthorDataVolSizeParameter:
          Ref: AuthorDataVolSizeParameter
        AuthorDataVolSnapshotParameter:
          Ref: AuthorDataVolSnapshotParameter
        AuthorImageParameter:
          Ref: AuthorImageParameter
        AuthorImageRootDevice:
          Fn::Select:
            - 0
            - Ref: ImageDevices
        AuthorImageDataDevice:
          Fn::Select:
            - 1
            - Ref: ImageDevices
        AuthorInstanceTypeParameter:
          Ref: AuthorInstanceTypeParameter
        AuthorLoadBalancerHealthCheckTargetParameter:
          Ref: AuthorLoadBalancerHealthCheckTargetParameter
        AuthorRootVolSizeParameter:
          Ref: AuthorRootVolSizeParameter
        ComputeKeyPairNameParameter:
          Ref: ComputeKeyPairNameParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        ELBCipherSuiteParameter:
          Ref: ELBCipherSuiteParameter
        InboundFromBastionHostSecurityGroupParameter:
          Ref: InboundFromBastionHostSecurityGroupParameter
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        NetworkStackPrefixParameter:
          Ref: NetworkStackPrefixParameter
        PrerequisitesStackPrefixParameter:
          Ref: PrerequisitesStackPrefixParameter
        UseAuthorDataVolSnapshotParameter:
          Ref: UseAuthorDataVolSnapshotParameter
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/author.yaml
    Type: AWS::CloudFormation::Stack
  ChaosMonkeyStack:
    Condition: CreateChaosMonkeyStackCondition
    DependsOn:
    - AuthorStack
    - PublishStack
    - AuthorDispatcherStack
    - PublishDispatcherStack
    - OrchestratorStack
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter:
          Ref: AemAwsStackProvisionerVersionParameter
        ChaosMonkeyASGAvailabilityZoneListParameter:
          Fn::Join:
            - ','
            - Ref: ChaosMonkeyASGAvailabilityZoneListParameter
        ChaosMonkeyImageParameter:
          Ref: ChaosMonkeyImageParameter
        ChaosMonkeyImageRootDevice:
          Fn::Select:
            - 0
            - Ref: ImageDevices
        ChaosMonkeyInstanceTypeParameter:
          Ref: ChaosMonkeyInstanceTypeParameter
        ChaosMonkeyRootVolSizeParameter:
          Ref: ChaosMonkeyRootVolSizeParameter
        ComputeKeyPairNameParameter:
          Ref: ComputeKeyPairNameParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        InboundFromBastionHostSecurityGroupParameter:
          Ref: InboundFromBastionHostSecurityGroupParameter
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        NetworkStackPrefixParameter:
          Ref: NetworkStackPrefixParameter
        PrerequisitesStackPrefixParameter:
          Ref: PrerequisitesStackPrefixParameter
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/chaos-monkey.yaml
    Type: AWS::CloudFormation::Stack
  OrchestratorStack:
    Properties:
      Parameters:
        AEMASGEventQueueName:
          Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-AEMASGEventQueueName
        AemAwsStackProvisionerVersionParameter:
          Ref: AemAwsStackProvisionerVersionParameter
        AuthorDispatcherStackArn:
          Ref: AuthorDispatcherStack
        AuthorStackArn:
          Ref: AuthorStack
        ComputeKeyPairNameParameter:
          Ref: ComputeKeyPairNameParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        InboundFromBastionHostSecurityGroupParameter:
          Ref: InboundFromBastionHostSecurityGroupParameter
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        MessagingStackArn:
          Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-MessagingStackName
        NetworkStackPrefixParameter:
          Ref: NetworkStackPrefixParameter
        OrchestratorASGAvailabilityZoneListParameter:
          Fn::Join:
            - ','
            - Ref: OrchestratorASGAvailabilityZoneListParameter
        OrchestratorDataVolSizeParameter:
          Ref: OrchestratorDataVolSizeParameter
        OrchestratorImageParameter:
          Ref: OrchestratorImageParameter
        OrchestratorImageRootDevice:
          Fn::Select:
            - 0
            - Ref: ImageDevices
        OrchestratorImageDataDevice:
          Fn::Select:
            - 1
            - Ref: ImageDevices
        OrchestratorInstanceTypeParameter:
          Ref: OrchestratorInstanceTypeParameter
        OrchestratorRootVolSizeParameter:
          Ref: OrchestratorRootVolSizeParameter
        PrerequisitesStackPrefixParameter:
          Ref: PrerequisitesStackPrefixParameter
        PublishDispatcherStackArn:
          Ref: PublishDispatcherStack
        PublishDispatcherStackName:
          # As of May '18, CloudFormation doesn't provide a way to retrieve the Stack Name with Fn::GetAtt or Ref functions
          # Resorting to parsing the ARN to obtain it
          # See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
          #      https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html
          Fn::Select:
            - 1
            - Fn::Split:
              - /
              - Ref: PublishDispatcherStack
        PublishStackArn:
          Ref: PublishStack
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/orchestrator.yaml
    Type: AWS::CloudFormation::Stack
  PublishDispatcherStack:
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter:
          Ref: AemAwsStackProvisionerVersionParameter
        ComputeKeyPairNameParameter:
          Ref: ComputeKeyPairNameParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        ELBCipherSuiteParameter:
          Ref: ELBCipherSuiteParameter
        InboundFromBastionHostSecurityGroupParameter:
          Ref: InboundFromBastionHostSecurityGroupParameter
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        NetworkStackPrefixParameter:
          Ref: NetworkStackPrefixParameter
        PrerequisitesStackPrefixParameter:
          Ref: PrerequisitesStackPrefixParameter
        PublishDispatcherASGAvailabilityZoneListParameter:
          Fn::Join:
            - ','
            - Ref: PublishDispatcherASGAvailabilityZoneListParameter
        PublishDispatcherASGCPUScalingParameters:
          Fn::Join:
            - ','
            - Ref: PublishDispatcherASGCPUScalingParameters
        PublishDispatcherASGConfigurationParameters:
          Fn::Join:
            - ','
            - Ref: PublishDispatcherASGConfigurationParameters
        PublishDispatcherDataVolSizeParameter:
          Ref: PublishDispatcherDataVolSizeParameter
        PublishDispatcherImageParameter:
          Ref: PublishDispatcherImageParameter
        PublishDispatcherImageRootDevice:
          Fn::Select:
            - 0
            - Ref: ImageDevices
        PublishDispatcherImageDataDevice:
          Fn::Select:
            - 1
            - Ref: ImageDevices
        PublishDispatcherInstanceTypeParameter:
          Ref: PublishDispatcherInstanceTypeParameter
        PublishDispatcherLoadBalancerHealthCheckTargetParameter:
          Ref: PublishDispatcherLoadBalancerHealthCheckTargetParameter
        PublishDispatcherLoadBalancerSchemeParameter:
          Ref: PublishDispatcherLoadBalancerSchemeParameter
        PublishDispatcherRootVolSizeParameter:
          Ref: PublishDispatcherRootVolSizeParameter
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/publish-dispatcher.yaml
    Type: AWS::CloudFormation::Stack
  PublishStack:
    Properties:
      Parameters:
        AemAwsStackProvisionerVersionParameter:
          Ref: AemAwsStackProvisionerVersionParameter
        ComputeKeyPairNameParameter:
          Ref: ComputeKeyPairNameParameter
        DataBucketNameParameter:
          Ref: DataBucketNameParameter
        InboundFromBastionHostSecurityGroupParameter:
          Ref: InboundFromBastionHostSecurityGroupParameter
        MainStackPrefixParameter:
          Ref: MainStackPrefixParameter
        NetworkStackPrefixParameter:
          Ref: NetworkStackPrefixParameter
        PrerequisitesStackPrefixParameter:
          Ref: PrerequisitesStackPrefixParameter
        PublishASGAvailabilityZoneListParameter:
          Fn::Join:
            - ','
            - Ref: PublishASGAvailabilityZoneListParameter
        PublishASGConfigurationParameters:
          Fn::Join:
            - ','
            - Ref: PublishASGConfigurationParameters
        PublishDataVolSizeParameter:
          Ref: PublishDataVolSizeParameter
        PublishDataVolSnapshotParameter:
          Ref: PublishDataVolSnapshotParameter
        PublishImageParameter:
          Ref: PublishImageParameter
        PublishImageRootDevice:
          Fn::Select:
            - 0
            - Ref: ImageDevices
        PublishImageDataDevice:
          Fn::Select:
            - 1
            - Ref: ImageDevices
        PublishInstanceTypeParameter:
          Ref: PublishInstanceTypeParameter
        PublishRootVolSizeParameter:
          Ref: PublishRootVolSizeParameter
        UsePublishDataVolSnapshotParameter:
          Ref: UsePublishDataVolSnapshotParameter
      TemplateURL:
        Fn::Sub: https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${MainStackPrefixParameter}/publish.yaml
    Type: AWS::CloudFormation::Stack
