AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  UsePublishDataVolSnapshotCondition:
    Fn::Equals:
    - Ref: UsePublishDataVolSnapshotParameter
    - true
Description: Create the Compute resources for the AEM Publish
Outputs:
  PublishAutoScalingGroup:
    Description: The Publish Auto Scaling Group
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-PublishAutoScalingGroup
    Value:
      Ref: PublishAutoScalingGroup
  PublishLaunchConfiguration:
    Description: The Publish Launch Configuration
    Value:
      Ref: PublishLaunchConfiguration
Parameters:
  AemAwsStackProvisionerVersionParameter:
    Description: AEM AWS Stack Provisioner version number
    Type: String
  ComputeKeyPairNameParameter:
    Description: The Compute Resources Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  NetworkStackPrefixParameter:
    Description: The AEM Stack Network Resources Stack Prefix
    Type: String
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
  PublishASGAvailabilityZoneListParameter:
    Description: The Publish Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  PublishASGConfigurationParameters:
    Description: The ASG configuration parameters
    Type: CommaDelimitedList
  PublishDataVolSizeParameter:
    Description: The Publish Instances Data EBS Volume Size
    Type: Number
  PublishDataVolSnapshotParameter:
    Description: The Publish Data Volume Snapshot Id
    Type: String
  PublishEnableVolEncryptionParameter:
    AllowedValues:
    - true
    - false
    Description: Wether to enable or disable EBS volume encryption.
    Type: String
  PublishImageParameter:
    Description: The Publish Image Id
    Type: AWS::EC2::Image::Id
  PublishImageRootDevice:
    Default: /dev/sda1
    Description: The root device name for the Publish Image Id
    Type: String
  PublishImageDataDevice:
    Default: /dev/sdb
    Description: The data device name for the Publish Image Id
    Type: String
  PublishInstanceTypeParameter:
    Description: The Publish Instance Type
    Type: String
  PublishRootVolSizeParameter:
    Description: Publish Instances Root EBS Volume Size
    Type: Number
  UsePublishDataVolSnapshotParameter:
    AllowedValues:
    - true
    - false
    Description: Wheather to use the Publish Snapshot Data Volume.
    Type: String
  HttpProxyParameter:
    Description: http_proxy parameter
    Type: String
  HttpsProxyParameter:
    Description: https_proxy parameter
    Type: String
  NoProxyParameter:
    Description: no_proxy parameter
    Type: String
Resources:
  PublishAutoScalingGroup:
    Properties:
      AvailabilityZones:
        Ref: PublishASGAvailabilityZoneListParameter
      Cooldown:
        Fn::Select:
          - 4
          - Ref: PublishASGConfigurationParameters
      DesiredCapacity:
        Fn::Select:
          - 2
          - Ref: PublishASGConfigurationParameters
      HealthCheckGracePeriod:
        Fn::Select:
          - 3
          - Ref: PublishASGConfigurationParameters
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: PublishLaunchConfiguration
      MaxSize:
        Fn::Select:
          - 0
          - Ref: PublishASGConfigurationParameters
      MetricsCollection:
      - Granularity: 1Minute
        Metrics:
        - GroupMinSize
        - GroupMaxSize
        - GroupDesiredCapacity
        - GroupInServiceInstances
        - GroupPendingInstances
        - GroupStandbyInstances
        - GroupTerminatingInstances
        - GroupTotalInstances
      MinSize:
        Fn::Select:
          - 1
          - Ref: PublishASGConfigurationParameters
      NotificationConfigurations:
      - NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        TopicARN:
          Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-AEMASGEventTopic
      Tags:
      - Key: Name
        PropagateAtLaunch: true
        Value: AEM Publish
      - Key: StackPrefix
        PropagateAtLaunch: true
        Value:
          Ref: MainStackPrefixParameter
      - Key: Component
        PropagateAtLaunch: true
        Value: publish
      VPCZoneIdentifier:
        Fn::Split:
        - ','
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackPrefixParameter}-PublishSubnetList
    Type: AWS::AutoScaling::AutoScalingGroup
  PublishLaunchConfiguration:
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName:
          Ref: PublishImageRootDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted:
            Ref: PublishEnableVolEncryptionParameter
          VolumeSize:
            Ref: PublishRootVolSizeParameter
          VolumeType: gp2
      - DeviceName:
          Ref: PublishImageDataDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted:
            Ref: PublishEnableVolEncryptionParameter
          SnapshotId:
            Fn::If:
            - UsePublishDataVolSnapshotCondition
            - Ref: PublishDataVolSnapshotParameter
            - Ref: AWS::NoValue
          VolumeSize:
            Ref: PublishDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishInstanceProfile
      ImageId:
        Ref: PublishImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishSecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\nexport no_proxy=${NoProxyParameter}\nexport http_proxy=${HttpProxyParameter}\nexport https_proxy=${HttpsProxyParameter}\n\
            \ source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${MainStackPrefixParameter} publish ${AemAwsStackProvisionerVersionParameter}\n"
    Type: AWS::AutoScaling::LaunchConfiguration

  WarningPublishMemoryHighAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      AlarmDescription: Memory Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Warning-Publish-MemoryHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: MemoryUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 80
    Type: AWS::CloudWatch::Alarm
  CriticalPublishMemoryHighAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      AlarmDescription: Memory Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Critical-Publish-MemoryHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: MemoryUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
  WarningPublishRootDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Warning-Publish-RootDiskSpaceHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
        - Name: MountPath
          Value: "/"
        - Name: Filesystem
          Value: "/"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 80
    Type: AWS::CloudWatch::Alarm
  CriticalPublishRootDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Critical-Publish-RootDiskSpaceHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
        - Name: MountPath
          Value: "/"
        - Name: Filesystem
          Value: "/"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
  WarningPublishDataDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Warning-Publish-DataDiskSpaceHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
        - Name: MountPath
          Value: "/mnt/ebs1"
        - Name: Filesystem
          Value: "/mnt/ebs1"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 80
    Type: AWS::CloudWatch::Alarm
  CriticalPublishDataDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Critical-Publish-DataDiskSpaceHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
        - Name: MountPath
          Value: "/mnt/ebs1"
        - Name: Filesystem
          Value: "/mnt/ebs1"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
  WarningPublishCPUUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      AlarmDescription: CPU Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Warning-Publish-CPUHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: "AWS/EC2"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      Period: 300
      Statistic: Maximum
      Threshold: 60
    Type: AWS::CloudWatch::Alarm
  CriticalPublishCPUUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      AlarmDescription: CPU Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Critical-Publish-CPUHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Ref: PublishAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: "AWS/EC2"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      Period: 300
      Statistic: Maximum
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
