AWSTemplateFormatVersion: '2010-09-09'
Description: Create the Compute resources for the AEM Publish Dispatcher
Outputs:
  PublishDispatcherAutoScalingGroup:
    Description: The Publish Dispatcher Auto Scaling Group
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-PublishDispatcherAutoScalingGroup
    Value:
      Ref: PublishDispatcherAutoScalingGroup
  PublishDispatcherLaunchConfiguration:
    Description: The Publish Dispatcher Launch Configuration
    Value:
      Ref: PublishDispatcherLaunchConfiguration
  PublishDispatcherLoadBalancer:
    Description: The Publish Dispatcher Load Balancer
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-PublishDispatcherLoadBalancer
    Value:
      Ref: PublishDispatcherLoadBalancer
  PublishDispatcherLoadBalancerDNSName:
    Description: The Publish Dispatcher Load Balancer DNSName
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-PublishDispatcherLoadBalancerDNSName
    Value:
      Fn::GetAtt:
      - PublishDispatcherLoadBalancer
      - DNSName
Parameters:
  AemAwsStackProvisionerVersionParameter:
    Description: AEM AWS Stack Provisioner version number
    Type: String
  ComputeKeyPairNameParameter:
    Description: The Compute Resources Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  ELBCipherSuiteParameter:
    Description: ELB Cipher Suite Policy
    Type: String
  InboundFromBastionHostSecurityGroupParameter:
    Description: Inbound Bound from Bastion Host Security Group Id
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  NetworkStackPrefixParameter:
    Description: The AEM Stack Network Resources Stack Prefix
    Type: String
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
  PublishDispatcherASGAvailabilityZoneListParameter:
    Description: The Publish Dispatcher Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  PublishDispatcherASGConfigurationParameters:
    Description: The ASG configuration parameters
    Type: CommaDelimitedList
  PublishDispatcherASGCPUScalingParameters:
    Description: The ASG CPU scaling parameters that extra Publish Dispatcher instances
      are scaled up/down at
    Type: CommaDelimitedList
  PublishDispatcherDataVolSizeParameter:
    Description: PublishDispatcher Instances Root EBS Volume Size
    Type: Number
  PublishDispatcherImageParameter:
    Description: The Publish Dispatcher Image Id
    Type: AWS::EC2::Image::Id
  PublishDispatcherImageRootDevice:
    Default: /dev/sda1
    Description: The root device name for the Publish Dispatcher Image Id
    Type: String
  PublishDispatcherImageDataDevice:
    Default: /dev/sdb
    Description: The data device name for the Publish Dispatcher Image Id
    Type: String
  PublishDispatcherInstanceTypeParameter:
    Description: The Publish Dispatcher Instance Type
    Type: String
  PublishDispatcherLoadBalancerHealthCheckTargetParameter:
    Description: AEM Publish Dispatcher ELB Health Check Target
    Type: String
  PublishDispatcherLoadBalancerSchemeParameter:
    Description: AEM Publish Dispatcher ELB Scheme
    Type: String
  PublishDispatcherRootVolSizeParameter:
    Description: PublishDispatcher Instances Root EBS Volume Size
    Type: Number
Resources:
  PublishDispatcherAutoScalingGroup:
    Properties:
      AvailabilityZones:
        Ref: PublishDispatcherASGAvailabilityZoneListParameter
      Cooldown:
        Fn::Select:
          - 4
          - Ref: PublishDispatcherASGConfigurationParameters
      DesiredCapacity:
        Fn::Select:
          - 2
          - Ref: PublishDispatcherASGConfigurationParameters
      HealthCheckGracePeriod:
        Fn::Select:
          - 3
          - Ref: PublishDispatcherASGConfigurationParameters
      HealthCheckType: ELB
      LaunchConfigurationName:
        Ref: PublishDispatcherLaunchConfiguration
      LoadBalancerNames:
      - Ref: PublishDispatcherLoadBalancer
      MaxSize:
        Fn::Select:
          - 0
          - Ref: PublishDispatcherASGConfigurationParameters
      MetricsCollection:
      - Granularity: 1Minute
        Metrics:
        - GroupMinSize
        - GroupMaxSize
        - GroupDesiredCapacity
        - GroupInServiceInstances
        - GroupPendingInstances
        - GroupStandbyInstances
        - GroupTerminatingInstances
        - GroupTotalInstances
      MinSize:
        Fn::Select:
          - 1
          - Ref: PublishDispatcherASGConfigurationParameters
      NotificationConfigurations:
      - NotificationTypes:
        - autoscaling:EC2_INSTANCE_LAUNCH
        - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        - autoscaling:EC2_INSTANCE_TERMINATE
        - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
        TopicARN:
          Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-AEMASGEventTopic
      Tags:
      - Key: Name
        PropagateAtLaunch: true
        Value: AEM Publish Dispatcher
      - Key: StackPrefix
        PropagateAtLaunch: true
        Value:
          Ref: MainStackPrefixParameter
      - Key: Component
        PropagateAtLaunch: true
        Value: publish-dispatcher
      - Key: ApplicationDescriptorUrl
        PropagateAtLaunch: true
        Value: PLACEHOLDER
      VPCZoneIdentifier:
        Fn::Split:
        - ','
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackPrefixParameter}-PublishDispatcherSubnetList
    Type: AWS::AutoScaling::AutoScalingGroup
  PublishDispatcherCPUHighAlarm:
    Properties:
      AlarmActions:
      - Ref: PublishDispatcherScaleUpPolicy
      AlarmDescription: Scale up if CPU Avg > X % for X minutes
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: PublishDispatcherAutoScalingGroup
      EvaluationPeriods:
        Fn::Select:
          - 2
          - Ref: PublishDispatcherASGCPUScalingParameters
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period:
        Fn::Select:
          - 1
          - Ref: PublishDispatcherASGCPUScalingParameters
      Statistic: Average
      Threshold:
        Fn::Select:
          - 0
          - Ref: PublishDispatcherASGCPUScalingParameters
      TreatMissingData: breaching
    Type: AWS::CloudWatch::Alarm
  PublishDispatcherCPULowAlarm:
    Properties:
      AlarmActions:
      - Ref: PublishDispatcherScaleDownPolicy
      AlarmDescription: Scale down if CPU Avg < X % for X minutes
      ComparisonOperator: LessThanThreshold
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: PublishDispatcherAutoScalingGroup
      EvaluationPeriods:
        Fn::Select:
          - 4
          - Ref: PublishDispatcherASGCPUScalingParameters
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period:
        Fn::Select:
          - 3
          - Ref: PublishDispatcherASGCPUScalingParameters
      Statistic: Average
      Threshold:
        Fn::Select:
          - 0
          - Ref: PublishDispatcherASGCPUScalingParameters
      TreatMissingData: breaching
    Type: AWS::CloudWatch::Alarm
  PublishDispatcherAtLeastOneUnHealthyAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: At least one Publish Dispatcher is Unhealthy
      AlarmName:
        Fn::Sub: ${MainStackPrefixParameter}-PublishDispatcherAtLeastOneUnHealthyAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
      - Name: LoadBalancerName
        Value:
          Ref: PublishDispatcherLoadBalancer
      EvaluationPeriods: 15
      MetricName: UnHealthyHostCount
      Namespace: AWS/ELB
      OKActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      Period: 60
      Statistic: Average
      Threshold: 1
    Type: AWS::CloudWatch::Alarm
  PublishDispatcherMoreThanOneUnHealthyAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      AlarmDescription: More than one Publish Dispatcher is Unhealthy
      AlarmName:
        Fn::Sub: ${MainStackPrefixParameter}-PublishDispatcherMoreThanOneUnHealthyAlarm
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: LoadBalancerName
        Value:
          Ref: PublishDispatcherLoadBalancer
      EvaluationPeriods: 1
      MetricName: UnHealthyHostCount
      Namespace: AWS/ELB
      OKActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AlarmNotificationTopic
      Period: 60
      Statistic: Average
      Threshold: 1
    Type: AWS::CloudWatch::Alarm
  PublishDispatcherLaunchConfiguration:
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName:
          Ref: PublishDispatcherImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDispatcherRootVolSizeParameter
          VolumeType: gp2
      - DeviceName:
          Ref: PublishDispatcherImageDataDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: PublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishDispatcherInstanceProfile
      ImageId:
        Ref: PublishDispatcherImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishDispatcherSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${MainStackPrefixParameter} publish-dispatcher\
            \ ${AemAwsStackProvisionerVersionParameter}\n"
    Type: AWS::AutoScaling::LaunchConfiguration
  PublishDispatcherLoadBalancer:
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        HealthyThreshold: '2'
        Interval: '30'
        Target:
          Ref: PublishDispatcherLoadBalancerHealthCheckTargetParameter
        Timeout: '5'
        UnhealthyThreshold: '10'
      Listeners:
      - InstancePort: '80'
        LoadBalancerPort: '80'
        Protocol: HTTP
      - InstancePort: '443'
        InstanceProtocol: HTTPS
        LoadBalancerPort: '443'
        Protocol: HTTPS
        SSLCertificateId:
          Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-SSLCertificateARN
        PolicyNames:
        - Ref: ELBCipherSuiteParameter
      Scheme:
        Ref: PublishDispatcherLoadBalancerSchemeParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-PublishDispatcherELBSecurityGroup
      Subnets:
        Fn::Split:
        - ','
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackPrefixParameter}-PublishDispatcherELBSubnetList
      Tags:
      - Key: Name
        Value: AEM Publish Dispatcher Load Balancer
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
    Type: AWS::ElasticLoadBalancing::LoadBalancer
  PublishDispatcherScaleDownPolicy:
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: PublishDispatcherAutoScalingGroup
      Cooldown: 480
      ScalingAdjustment: -1
    Type: AWS::AutoScaling::ScalingPolicy
  PublishDispatcherScaleUpPolicy:
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Ref: PublishDispatcherAutoScalingGroup
      Cooldown: 480
      ScalingAdjustment: 1
    Type: AWS::AutoScaling::ScalingPolicy
