---
- name: AEM Network CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Create CloudFormation Stack that Exports AEM Network Resources
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ network_exports.stack_name }}"
        state: present
        region: "{{ aws.region }}"
        disable_rollback: true
        template: "../../../cloudformation/network/network-exports.yaml"
        template_parameters:
          StackPrefix: "{{ stack_prefix }}"
          VPCId: "{{ network_exports.VPCId }}"
          AuthorPublishDispatcherSubnet: "{{ network_exports.AuthorPublishDispatcherSubnet }}"
          PublishDispatcherELBSubnetList: "{{ network_exports.PublishDispatcherELBSubnetList }}"
          PublishDispatcherSubnetList: "{{ network_exports.PublishDispatcherSubnetList }}"
          PublishSubnetList: "{{ network_exports.PublishSubnetList }}"
          AuthorPrimarySubnet: "{{ network_exports.AuthorPrimarySubnet }}"
          AuthorStandbySubnet: "{{ network_exports.AuthorStandbySubnet }}"
          AuthorELBSubnetList: "{{ network_exports.AuthorELBSubnetList }}"
          AuthorDispatcherELBSubnetList: "{{ network_exports.AuthorDispatcherELBSubnetList }}"
          AuthorDispatcherSubnetList: "{{ network_exports.AuthorDispatcherSubnetList }}"
          ToolSubnetList: "{{ network_exports.ToolSubnetList }}"
          PublicRouteTable: "{{ network_exports.PublicRouteTable }}"
          PrivateRouteTable: "{{ network_exports.PrivateRouteTable }}"
      tags:
        - create

    - name: Check if a Stack Exists
      command: >
               aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ network_exports.stack_name }}"
               --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ network_exports.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Network Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ network_exports.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
