---
- name: AEM VPC CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM VPC Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ ec2_vpc.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/network/vpc.yaml"
        template_parameters:
          Ec2VpcCidrBlockParameter: "{{ ec2_vpc.cidr_block }}"
          Ec2VpcTagNameParameter: "{{ stack_prefix }}-{{ ec2_vpc.tag_name }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ ec2_vpc.stack_name }}" --query 'Stacks[].StackName'
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ ec2_vpc.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM VPC Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ ec2_vpc.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"        
      tags:
      - delete
