AWSTemplateFormatVersion: '2010-09-09'
Description: Create Nat Gateway and add to private Route Table for AEM Stack
Outputs:
  Ec2NatGateway:
    Description: The Nat-Gatway for the AEM Stack
    Value:
      Ref: Ec2NatGateway
Parameters:
  Ec2NatGatewayElasticIpAllocationIdParameter:
    Default: eipalloc-32711957
    Description: The EC2 Nat Gateway Elastic Ip Allocation Id
    Type: String
  StackPrefix:
    Default: ''
    Description: Used to Namespace the Exported Resources
    Type: String
Resources:
  Ec2NatGateway:
    Properties:
      AllocationId:
        Ref: Ec2NatGatewayElasticIpAllocationIdParameter
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: ${StackPrefix}-PublishDispatcherELBSubnetA
    Type: AWS::EC2::NatGateway
  PrivateInternetGatewayRoute:
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: Ec2NatGateway
      RouteTableId:
        Fn::ImportValue:
          Fn::Sub: ${StackPrefix}-PrivateRouteTable
    Type: AWS::EC2::Route
