---

AWSTemplateFormatVersion: '2010-09-09'
Description: Export Network Resources to Make It Available for Other Stacks
Outputs:
  AuthorDispatcherELBSubnetList:
    Description: Comma-separated Author Dispatcher ELB Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorDispatcherELBSubnetList
    Value:
      Ref: AuthorDispatcherELBSubnetList
  AuthorDispatcherSubnetList:
    Description: Comma-separated Author Dispatcher Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorDispatcherSubnetList
    Value:
      Ref: AuthorDispatcherSubnetList
  AuthorPublishDispatcherSubnet:
    Description: The Author Publish Dispatcher Subnet
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorPublishDispatcherSubnet
    Value:
      Ref: AuthorPublishDispatcherSubnet
  AuthorPrimarySubnet:
    Description: The Author Primary Subnet
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorPrimarySubnet
    Value:
      Ref: AuthorPrimarySubnet
  AuthorStandbySubnet:
    Description: The Author Standby Subnet
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorStandbySubnet
    Value:
      Ref: AuthorStandbySubnet
  AuthorELBSubnetList:
    Description: Comma-separated Author ELB Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-AuthorELBSubnetList
    Value:
      Ref: AuthorELBSubnetList
  ChaosMonkeySubnetList:
    Description: Comma-separated ChaosMonkey Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-ChaosMonkeySubnetList
    Value:
      Ref: ToolSubnetList
  OrchestratorSubnetList:
    Description: Comma-separated Orchestrator Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-OrchestratorSubnetList
    Value:
      Ref: ToolSubnetList
  PrivateRouteTable:
    Description: The Private Route Table for AEM OpenCloud VPC
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PrivateRouteTable
    Value:
      Ref: PrivateRouteTable
  PublicRouteTable:
    Description: The Public Route Table for AEM OpenCloud VPC
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublicRouteTable
    Value:
      Ref: PublicRouteTable
  PublishDispatcherELBSubnetList:
    Description: Comma-separated Publish Dispatcher ELB Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishDispatcherELBSubnetList
    Value:
      Ref: PublishDispatcherELBSubnetList
  PublishDispatcherSubnetList:
    Description: Comma-separated Publish Dispatcher Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishDispatcherSubnetList
    Value:
      Ref: PublishDispatcherSubnetList
  PublishSubnetList:
    Description: Comma-separated Publish Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-PublishSubnetList
    Value:
      Ref: PublishSubnetList
  ToolSubnetList:
    Description: Comma-separated Tool Subnet List
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-ToolSubnetList
    Value:
      Ref: ToolSubnetList
  VPCId:
    Description: AEM VPC Id
    Export:
      Name:
        Fn::Sub: ${StackPrefix}-VPCId
    Value:
      Ref: VPCId
Parameters:
  AuthorDispatcherELBSubnetList:
    Description: Comma-separated Author Dispatcher ELB Subnet List
    Type: String
  AuthorDispatcherSubnetList:
    Description: Comma-separated Author Dispatcher Subnet List
    Type: String
  AuthorPublishDispatcherSubnet:
    Description: The Author Publish Dispatcher Subnet
    Type: String
  AuthorPrimarySubnet:
    Description: The Author Primary Subnet
    Type: String
  AuthorStandbySubnet:
    Description: The Author Standby Subnet
    Type: String
  AuthorELBSubnetList:
    Description: Comma-separated Author ELB Subnet List
    Type: String
  PrivateRouteTable:
    Default: ''
    Description: The Private Route Table for AEM OpenCloud VPC
    Type: String
  PublicRouteTable:
    Default: ''
    Description: The Public Route Table for AEM OpenCloud VPC
    Type: String
  PublishDispatcherELBSubnetList:
    Description: Comma-separated Publish Dispatcher ELB Subnet List
    Type: String
  PublishDispatcherSubnetList:
    Description: Comma-separated Publish Dispatcher Subnet List
    Type: String
  PublishSubnetList:
    Description: Comma-separated Publish Subnet List
    Type: String
  StackPrefix:
    Default: ''
    Description: Used to Namespace the Exported Resources
    Type: String
  ToolSubnetList:
    Default: ''
    Description: Comma-separated Tool Subnet List
    Type: String
  VPCId:
    Description: AEM VPC Id
    Type: AWS::EC2::VPC::Id
Resources:
  DummyGroup:
    Properties:
      GroupDescription: Dummy Security Group to Allow Stack to Work
      VpcId:
        Ref: VPCId
    Type: AWS::EC2::SecurityGroup
