AWSTemplateFormatVersion: '2010-09-09'
Description: Export existing Instance Profiles for AEM Stack
Outputs:
  AuthorPublishDispatcherInstanceProfile:
    Description: The Author Publish Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorPublishDispatcherInstanceProfile
    Value:
      Ref: AuthorPublishDispatcherInstanceProfileParameter
Parameters:
  AuthorPublishDispatcherInstanceProfileParameter:
    Description: The Author Publish Dispatcher Instance Profile ARN
    Type: String
  PrerequisitesStackPrefixParameter:
    Description: The AEM Prerequisite Resources Stack Prefix
    Type: String
Resources:
  DummyParameter:
    Properties:
      Description: Dummy resource required for a CF stack
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-DummyParameter
      Type: String
      Value:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-DummyParameter
    Type: AWS::SSM::Parameter
