AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  EBSVolumeEncryptionCMKAddManagedPolicyCondition:
    Fn::And:
      - Fn::Equals:
          - Fn::Select:
            - 0
            - Ref: AWSEncryptionParameters
          - true
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                - 1
                - Ref: AWSEncryptionParameters
              - 'overwrite-me'
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                - 2
                - Ref: AWSEncryptionParameters
              - 'overwrite-me'
  S3CMKAddManagedPolicyCondition:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
            - 3
            - Ref: AWSEncryptionParameters
          - 'overwrite-me'
Description: Create Instance Profiles for AEM Stack
Outputs:
  AuthorPublishDispatcherInstanceProfile:
    Description: The Author Publish Dispatcher Instance Profile
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorPublishDispatcherInstanceProfile
    Value:
      Ref: AuthorPublishDispatcherInstanceProfile
  AuthorPublishDispatcherRoleArn:
    Description: The Author Publish Dispatcher Instance Role ARN
    Export:
      Name:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorPublishDispatcherRole
    Value:
      Fn::GetAtt: AuthorPublishDispatcherRole.Arn
Parameters:
  PrerequisitesStackPrefixParameter:
    Description: The AEM Prerequisite Resources Stack Prefix
    Type: String
  AWSEncryptionParameters:
    Description: |
      A list of AWS Encyrption parameters.
      List hast to be containing the following values in the following order:
        - Boolean for enabling/disabling EBS Volume encryption
        - KMS Key ID used for EBS Volume encryption
        - Managed Policy ARN for EBS Volume encryption
        - Managed Policy ARN for accessing S3 CMK
    Type: List<String>
Resources:
  AuthorPublishDispatcherInstanceProfile:
    Properties:
      Path: /
      Roles:
      - Ref: AuthorPublishDispatcherRole
    Type: AWS::IAM::InstanceProfile
  AuthorPublishDispatcherRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      - Fn::If:
          - EBSVolumeEncryptionCMKAddManagedPolicyCondition
          - Fn::Select:
              - 2
              - Ref: AWSEncryptionParameters
          - Ref: AWS::NoValue
      - Fn::If:
          - S3CMKAddManagedPolicyCondition
          - Fn::Select:
              - 3
              - Ref: AWSEncryptionParameters
          - Ref: AWS::NoValue
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ec2:Describe*
            - ec2:CreateTags
            - ec2:AttachVolume
            - ec2:CreateVolume
            - ec2:DetachVolume
            - ec2:CreateSnapshot
            - ec2:ModifyInstanceAttribute
            - autoscaling:CreateLaunchConfiguration
            - autoscaling:DeleteLaunchConfiguration
            - autoscaling:DescribeLaunchConfigurations
            - autoscaling:DescribeAutoScalingGroups
            - autoscaling:UpdateAutoScalingGroup
            - autoscaling:CreateOrUpdateTags
            - iam:PassRole
            - cloudwatch:PutMetricData
            - acm:GetCertificate
            - secretsmanager:GetSecretValue
            Effect: Allow
            Resource: '*'
          - Action:
            - s3:Get*
            - s3:List*
            - s3:Put*
            Effect: Allow
            Resource: '*'
          - Action:
            - logs:*
            Effect: Allow
            Resource:
            - arn:aws:logs:*:*:*
          Version: '2012-10-17'
        PolicyName: AuthorPublishDispatcherRolePolicy
      RoleName:
        Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorPublishDispatcherRole
    Type: AWS::IAM::Role
