AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  UseAuthorDataVolSnapshotCondition:
    Fn::Equals:
      - Fn::Select:
          - 2
          - Ref: AuthorPublishDispatcherVolParameter
      - true
  UsePublishDataVolSnapshotCondition:
    Fn::Equals:
      - Fn::Select:
          - 3
          - Ref: AuthorPublishDispatcherVolParameter
      - true
  UseCMKEBSVolumeEncryptionCondition:
    Fn::And:
      - Fn::Equals:
          - Fn::Select:
            - 4
            - Ref: AuthorPublishDispatcherVolParameter
            # To support the deprecrated configuration parameters,
            # [aem_component].enable_vol_encryption
            #
            # The new parameter is not support yet.
            # - 0
            # - Ref: AWSEncryptionParameters
          - true
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                - 1
                - Ref: AWSEncryptionParameters
              - 'overwrite-me'
Description: Create AEM Consolidated Main Resources Stacks
Parameters:
  AemAwsStackProvisionerVersionParameter:
    Description: AEM AWS Stack Provisioner version number
    Type: String
  AuthorDataVolSnapshotParameter:
    Description: The Author Data Volume Snapshot Id
    Type: String
  AssociatePublicIpAddressParameter:
    Description: Add Public IP Address to instance
    Type: String
  AuthorPublishDispatcherDNSRecordSetNameParameter:
    Description: Author Publish Dispatcher DNS Record Set Name
    Type: String
  AuthorPublishDispatcherImageParameter:
    Description: AMI Id used for the Host
    Type: AWS::EC2::Image::Id
  ImageDevices:
    Default: "/dev/sda1, /dev/sdb  /dev/sdc"
    Description: The device names for the Image Id
    Type: List<String>
  AuthorPublishDispatcherInstanceTypeParameter:
    Description: The Author Publish Dispatcher Instance Type
    Type: String
  AuthorPublishDispatcherVolParameter:
    Description: Author Publish Dispatcher Instances EBS volume parameters
    Type: List<String>
  ComputeKeyPairNameParameter:
    Description: The Compute Resources Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName
  DNSRecordSetTTL:
    Description: Record Set TTL value
    Type: String
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  AWSEncryptionParameters:
    Description: |
      A list of AWS Encyrption parameters.
      List hast to be containing the following values in the following order:
        - Boolean for enabling/disabling EBS Volume encryption
        - KMS Key ID used for EBS Volume encryption
    Type: List<String>
  MainStackPrefixParameter:
    Description: The AEM Stack Main Resources Stack Prefix
    Type: String
  NetworkStackPrefixParameter:
    Description: The AEM Stack Network Resources Stack Prefix
    Type: String
  PrerequisitesStackPrefixParameter:
    Description: The AEM Prerequisite Resources Stack Prefix
    Type: String
  PublishDataVolSnapshotParameter:
    Description: The Publish Data Volume Snapshot Id
    Type: String
  Route53HostedZoneNameParameter:
    Description: Route53 Hosted Zone Name the Record Set will be Created in
    Type: String
Resources:
  AuthorPublishDispatcherInstance:
    Properties:
      BlockDeviceMappings:
      - DeviceName:
          Fn::Select:
            - 0
            - Ref: ImageDevices
        Ebs:
          DeleteOnTermination: true
          Encrypted:
            Fn::Select:
              - 4
              - Ref: AuthorPublishDispatcherVolParameter
              # To support the deprecrated configuration parameters,
              # [aem_component].enable_vol_encryption
              #
              # The new parameter is not support yet.
              # - 0
              # - Ref: AWSEncryptionParameters
          KmsKeyId:
              Fn::If:
              - UseCMKEBSVolumeEncryptionCondition
              - Fn::Select:
                  - 1
                  - Ref: AWSEncryptionParameters
              - Ref: AWS::NoValue
          VolumeSize:
            Fn::Select:
              - 0
              - Ref: AuthorPublishDispatcherVolParameter
          VolumeType: gp2
      - DeviceName:
          Fn::Select:
            - 1
            - Ref: ImageDevices
        Ebs:
          DeleteOnTermination: true
          Encrypted:
            Fn::Select:
              - 4
              - Ref: AuthorPublishDispatcherVolParameter
              # To support the deprecrated configuration parameters,
              # [aem_component].enable_vol_encryption
              #
              # The new parameter is not support yet.
              # - 0
              # - Ref: AWSEncryptionParameters
          KmsKeyId:
              Fn::If:
              - UseCMKEBSVolumeEncryptionCondition
              - Fn::Select:
                  - 1
                  - Ref: AWSEncryptionParameters
              - Ref: AWS::NoValue
          SnapshotId:
            Fn::If:
            - UseAuthorDataVolSnapshotCondition
            - Ref: AuthorDataVolSnapshotParameter
            - Ref: AWS::NoValue
          VolumeSize:
            Fn::Select:
              - 1
              - Ref: AuthorPublishDispatcherVolParameter
          VolumeType: gp2
      - DeviceName:
          Fn::Select:
            - 2
            - Ref: ImageDevices
        Ebs:
          DeleteOnTermination: true
          Encrypted:
            Fn::Select:
              - 4
              - Ref: AuthorPublishDispatcherVolParameter
              # To support the deprecrated configuration parameters,
              # [aem_component].enable_vol_encryption
              #
              # The new parameter is not support yet.
              # - 0
              # - Ref: AWSEncryptionParameters
          KmsKeyId:
              Fn::If:
              - UseCMKEBSVolumeEncryptionCondition
              - Fn::Select:
                  - 1
                  - Ref: AWSEncryptionParameters
              - Ref: AWS::NoValue
          SnapshotId:
            Fn::If:
            - UsePublishDataVolSnapshotCondition
            - Ref: PublishDataVolSnapshotParameter
            - Ref: AWS::NoValue
          VolumeSize:
            Fn::Select:
              - 1
              - Ref: AuthorPublishDispatcherVolParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorPublishDispatcherInstanceProfile
      ImageId:
        Ref: AuthorPublishDispatcherImageParameter
      InstanceType:
        Ref: AuthorPublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      NetworkInterfaces:
      - AssociatePublicIpAddress:
          Ref: AssociatePublicIpAddressParameter
        DeviceIndex: '0'
        GroupSet:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-AuthorPublishDispatcherSecurityGroup
        SubnetId:
          Fn::ImportValue:
            Fn::Sub: ${NetworkStackPrefixParameter}-AuthorPublishDispatcherSubnet
      Tags:
      - Key: StackPrefix
        Value:
          Ref: MainStackPrefixParameter
      - Key: Name
        Value: AEM Author Publish Dispatcher
      - Key: Component
        Value: author-publish-dispatcher
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${MainStackPrefixParameter} author-publish-dispatcher\
            \ ${AemAwsStackProvisionerVersionParameter}\n"
    Type: AWS::EC2::Instance
  AuthorPublishDispatcherRoute53RecordSet:
    Properties:
      HostedZoneName:
        Ref: Route53HostedZoneNameParameter
      Name:
        Fn::Sub: ${AuthorPublishDispatcherDNSRecordSetNameParameter}.${Route53HostedZoneNameParameter}
      ResourceRecords:
      - Fn::GetAtt:
        - AuthorPublishDispatcherInstance
        - PrivateIp
      TTL:
        Ref: DNSRecordSetTTL
      Type: A
    Type: AWS::Route53::RecordSet
