name: Publish
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 5.19.0.3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: shinesolutions
          password: ${{ secrets.SHINEOPENSOURCE_GITHUB_TOKEN }}
      - uses: ./.github/actions/publish-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
